EXTRA = """    /* End screen */
    'end.won':    '🏆 ಬ್ಯಾಚ್ ಬಿಡುಗಡೆಯಾಯಿತು!',
    'end.lost':   '⏱ ಸಮಯ ಮುಗಿಯಿತು — ಬ್ಯಾಚ್ ಬಿಡುಗಡೆಯಾಗಿಲ್ಲ',
    'end.new_game': '↺ ಹೊಸ ಆಟ',
    'end.hq_breakdown_h': 'ಗುಪ್ತ ಪ್ರಶ್ನೆ ಫಲಿತಾಂಶ',
    'modal.close':  'ಮುಚ್ಚಿ',
    'modal.submit': 'ಸಲ್ಲಿಸಿ',
    'topic.calibration': 'ಮಾಪನಾಂಶ',
    'topic.batch_records': 'ಬ್ಯಾಚ್ ದಾಖಲೆ',
    'topic.visual_inspection': 'ದೃಶ್ಯ ತಪಾಸಣೆ',
    'topic.defect_class': 'ದೋಷ ವರ್ಗೀಕರಣ',
    'topic.sop_compliance': 'SOP ಅನುಸರಣೆ',
    'topic.risk_thinking': 'ಅಪಾಯ ಆಧಾರಿತ ಚಿಂತನೆ',
    'start.how_content': '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px 20px;line-height:1.9;"><div>🔍 <strong style="color:var(--text);">ಹಾಟ್‌ಸ್ಪಾಟ್ ಪರಿಶೀಲಿಸಿ</strong> ಪ್ರತಿ ಪ್ರದೇಶದಲ್ಲಿ ಸುಳಿವು ಹುಡುಕಿ ವಸ್ತು ಸಂಗ್ರಹಿಸಿ</div><div>🎒 <strong style="color:var(--text);">ವಸ್ತು ಆಯ್ಕೆ ಮಾಡಿ</strong> ದಾಸ್ತಾನಿನಿಂದ, ನಂತರ ಹಾಟ್‌ಸ್ಪಾಟ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಬಳಸಿ</div><div>🧩 <strong style="color:var(--text);">ಒಗಟು ಬಿಡಿಸಿ</strong> — ಪ್ರತಿ ಉತ್ತರ ನೈಜ ಗುಣಮಟ್ಟ ತತ್ತ್ವದ ಮೇಲೆ ನಿಂತಿದೆ</div><div>📋 <strong style="color:var(--text);">ಟಿಪ್ಪಣಿ ಪರಿಶೀಲಿಸಿ</strong> — ಸುಳಿವು ಮತ್ತು ಸಂಗತಿ ತಾನಾಗಿ ದಾಖಲಾಗುತ್ತವೆ</div><div>💬 <strong style="color:var(--text);">ತಂಡ ಚಾಟ್ ಬಳಸಿ</strong> — ನೈಜ ಸಮಯದಲ್ಲಿ ತಂಡದೊಂದಿಗೆ ಸಮನ್ವಯ ಮಾಡಿ</div><div>🔑 <strong style="color:var(--text);">ವೈಯಕ್ತಿಕವಾಗಿ ಕಾರ್ಯ ಪೂರ್ಣಗೊಳಿಸಿ</strong> — ಪ್ರತಿ ಆಟಗಾರ ತಂಡ ಮುಂದುವರಿಯಲು ಪ್ರತಿ ಒಗಟು ಸ್ವಯಂ ಬಿಡಿಸಬೇಕು</div></div><div style="margin-top:10px;padding:8px 12px;background:rgba(0,153,230,0.07);border-left:3px solid var(--accent);border-radius:2px;font-size:0.77rem;color:var(--dim);line-height:1.7;"><strong style="color:var(--text);">5 ಪ್ರದೇಶ</strong> ಮತ್ತು <strong style="color:var(--text);">11 ಒಗಟು</strong> <strong style="color:var(--text);">30 ನಿಮಿಷ</strong>ದಲ್ಲಿ ಪೂರ್ಣಗೊಳಿಸಬೇಕು. ಪ್ರಗತಿ ಆದಂತೆ ಪ್ರದೇಶ ತೆರೆದುಕೊಳ್ಳುತ್ತದೆ — ಮುಂದೆ ಹೋಗಲು ಸಾಧ್ಯವಿಲ್ಲ.</div>',
    'start.rules_content': '<table style="width:100%;border-collapse:collapse;"><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;width:28px;font-size:1rem;">👥</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ತಂಡ ಗಾತ್ರ:</strong> 3 – 5 ಸದಸ್ಯರು. ಆಟ ಪ್ರಾರಂಭವಾಗುವ ಮೊದಲು ಎಲ್ಲರೂ ಸಂಪರ್ಕಿತರಾಗಿರಬೇಕು.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">⏱️</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಏಕಕಾಲ ಪ್ರಾರಂಭ:</strong> ಪ್ರತಿ ಆಟಗಾರ <em>"ನಾನು ತಯಾರು"</em> ಕ್ಲಿಕ್ ಮಾಡಬೇಕು. ಟೈಮರ್ ಎಲ್ಲರಿಗೆ ಒಟ್ಟಿಗೆ ಪ್ರಾರಂಭ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">👤</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ವೈಯಕ್ತಿಕ ಅವಶ್ಯಕತೆ:</strong> ಪ್ರತಿ ಆಟಗಾರ ಸ್ವತಂತ್ರವಾಗಿ ಪ್ರತಿ ಕಾರ್ಯ ಪೂರ್ಣಗೊಳಿಸಬೇಕು. ಎಲ್ಲ ಕಾರ್ಯ ಸ್ವಯಂ ಮಾಡದೆ ಕೋಣೆ ದಾಟಲು ಸಾಧ್ಯವಿಲ್ಲ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">⏸</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಸಂಪರ್ಕ ಕಡಿತದಲ್ಲಿ ವಿರಾಮ:</strong> ತಂಡ ಸದಸ್ಯ ಸಂಪರ್ಕ ಕಡಿದರೆ ಆಟ ತಾನಾಗಿ ವಿರಾಮ. ಎಲ್ಲರೂ ಮರಳಿದ ನಂತರ ಟೈಮರ್ ಮರಳ್ತದೆ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">❓</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಗುಪ್ತ ಪ್ರಶ್ನೆ:</strong> ಪ್ರತಿ ಕೋಣೆ 2 ಐಚ್ಛಿಕ ಬೋನಸ್ ಪ್ರಶ್ನೆ ಹೊಂದಿದೆ. ಸರಿ ಉತ್ತರ +20 ಅಂಕ. ತಪ್ಪು ಉತ್ತರಕ್ಕೆ ಯಾವ ದಂಡವಿಲ್ಲ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">🚪</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಪ್ರದೇಶ ಲಾಕ್:</strong> ಹಿಂದಿನ ಕಾರ್ಯ ಪೂರ್ಣವಾಗುವವರೆಗೆ ಪ್ರತಿ ಪ್ರದೇಶ ಲಾಕ್ — ಕ್ರಮದಲ್ಲಿ ಪೂರ್ಣಗೊಳಿಸಿ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">❌</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ತಪ್ಪು ಉತ್ತರ:</strong> ಪ್ರತಿ ತಪ್ಪು ಉತ್ತರ ಅಂತಿಮ ಅಂಕದಿಂದ <strong style="color:var(--danger);">50 ಅಂಕ</strong> ಕಡಿತ — ಸಲ್ಲಿಸುವ ಮೊದಲು ಯೋಚಿಸಿ.</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:7px 8px 7px 0;font-size:1rem;">💡</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಸಲಹೆ:</strong> ಪ್ರತಿ ಪ್ರದೇಶ ಒಂದು ಸಲಹೆ ಲಭ್ಯ. ಸಲಹೆ ಬಳಕೆ <strong style="color:var(--danger);">−60 ಸೆಕೆಂಡ್</strong> ಮತ್ತು <strong style="color:var(--danger);">−50 ಅಂಕ</strong> ಕಡಿತ. ಸಲಹೆ ಸೂಕ್ಷ್ಮ — ನೇರ ಉತ್ತರ ನೀಡುವುದಿಲ್ಲ.</td></tr><tr><td style="padding:7px 8px 7px 0;font-size:1rem;">🏁</td><td style="padding:7px 0;color:var(--dim);"><strong style="color:var(--text);">ಒಂದು ಪ್ರಯತ್ನ:</strong> ಪ್ರತಿ ತಂಡ ಒಮ್ಮೆ ಮಾತ್ರ ಆಡಬಹುದು. ಫಲಿತಾಂಶ ಅಂತಿಮ ಮತ್ತು ಲೀಡರ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪ್ರಕಟಿಸಲಾಗುತ್ತದೆ.</td></tr></table>',
    'start.scoring_content': '<table style="width:100%;border-collapse:collapse;margin-bottom:10px;"><thead><tr style="border-bottom:1px solid var(--border);"><th style="text-align:left;font-size:0.65rem;text-transform:uppercase;letter-spacing:1.5px;color:var(--dim);padding:5px 0;">ಏನು</th><th style="text-align:right;font-size:0.65rem;text-transform:uppercase;letter-spacing:1.5px;color:var(--dim);padding:5px 0;">ಅಂಕ</th></tr></thead><tbody><tr style="border-bottom:1px solid #14162a;"><td style="padding:8px 0;color:var(--dim);">✅ ಪ್ರತಿ ಒಗಟು ಬಿಡಿಸಿದ್ದಕ್ಕೆ</td><td style="padding:8px 0;text-align:right;color:var(--accent2);font-weight:bold;">+200 ಅಂಕ</td></tr><tr style="border-bottom:1px solid #14162a;"><td style="padding:8px 0;color:var(--dim);">⏱️ ಗಡಿಯಾರದಲ್ಲಿ ಉಳಿದ ಪ್ರತಿ ಸೆಕೆಂಡ್ <em>(ಗೆದ್ದರೆ ಮಾತ್ರ)</em></td><td style="padding:8px 0;text-align:right;color:var(--accent2);font-weight:bold;">+2 ಅಂಕ / ಸೆ</td></tr><tr style="border-bottom:1px solid #14162a;"><td style="padding:8px 0;color:var(--dim);">❌ ಪ್ರತಿ ತಪ್ಪು ಉತ್ತರ</td><td style="padding:8px 0;text-align:right;color:var(--danger);font-weight:bold;">−50 ಅಂಕ</td></tr><tr><td style="padding:8px 0;color:var(--dim);">💡 ಸಲಹೆ ಬಳಕೆ</td><td style="padding:8px 0;text-align:right;color:var(--danger);font-weight:bold;">−50 ಅಂಕ &amp; −60ಸೆ</td></tr></tbody></table><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;"><div style="background:#0a0c18;border:1px solid var(--border);border-radius:6px;padding:10px 14px;text-align:center;"><div style="font-size:0.65rem;text-transform:uppercase;letter-spacing:1.5px;color:var(--dim);margin-bottom:4px;">ಗರಿಷ್ಠ ಒಗಟು ಅಂಕ</div><div style="font-size:1.2rem;font-weight:bold;color:var(--accent2);">2,200</div><div style="font-size:0.68rem;color:var(--dim);">11 × 200</div></div><div style="background:#0a0c18;border:1px solid var(--border);border-radius:6px;padding:10px 14px;text-align:center;"><div style="font-size:0.65rem;text-transform:uppercase;letter-spacing:1.5px;color:var(--dim);margin-bottom:4px;">ಗರಿಷ್ಠ ಸಮಯ ಬೋನಸ್</div><div style="font-size:1.2rem;font-weight:bold;color:var(--accent2);">3,600</div><div style="font-size:0.68rem;color:var(--dim);">1,800 ಸೆ × 2</div></div></div><div style="margin-top:8px;padding:8px 12px;background:rgba(255,215,0,0.06);border:1px solid rgba(255,215,0,0.25);border-radius:4px;text-align:center;font-size:0.78rem;color:#ffd700;">🏆 ಗರಿಷ್ಠ ಸಾಧ್ಯ ಅಂಕ: <strong>5,800 ಅಂಕ</strong> — ಎಲ್ಲ ಒಗಟು ಬಿಡಿಸಿ, ತಪ್ಪಿಲ್ಲ, ಸಲಹೆ ಇಲ್ಲ, ತಕ್ಷಣ ಮುಗಿಸಿ</div>',
    'start.connecting': 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…',
    'lobby.need_3': 'ಪ್ರಾರಂಭಿಸಲು ಕನಿಷ್ಠ 3 ಸದಸ್ಯರು ಬೇಕು.',
    'lobby.waiting_ready': 'ಎಲ್ಲ ಸದಸ್ಯರು ತಯಾರು ಕ್ಲಿಕ್ ಮಾಡಲು ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ.',
    'lobby.all_5': 'ಎಲ್ಲ 5 ಸದಸ್ಯರು ಸಂಪರ್ಕಿತರಾಗಿದ್ದಾರೆ!',
    'header.title': '🏭 MediSeal — ಗುಣಮಟ್ಟ ಸಪ್ತಾಹ',
    'header.motto': 'ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ಪ್ರಗತಿ · ಪ್ರತಿ ವಿವರದಲ್ಲೂ ಗುಣಮಟ್ಟ',
    'side.inventory': 'ದಾಸ್ತಾನು',
    'side.field_notes': 'ಟಿಪ್ಪಣಿ',
    'side.group_chat': 'ತಂಡ ಚಾಟ್',
    'side.areas': 'ಪ್ರದೇಶಗಳು',
    'side.no_entries': 'ಇನ್ನೂ ಯಾವ ನಮೂದು ಇಲ್ಲ.',
    'side.chat_ph': 'ಮೊದಲು ಸಂಪರ್ಕಿಸಿ…',
    'end.msg_won': 'ಅಮೋಘ ಕಾರ್ಯ! ನಿಮ್ಮ ತಂಡ ಎಲ್ಲ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ, ಮೂಲ ಕಾರಣ ಗುರುತಿಸಿ, ಅಸಂಗತ ಬ್ಯಾಚ್ ಸರಿಯಾಗಿ ನಿರ್ಣಯಿಸಿತು — ರೋಗಿಗಳನ್ನು ಮತ್ತು MediSeal ನ GMP ಪರವಾನಗಿ ರಕ್ಷಿಸಿತು.',
    'end.msg_lost': 'ಸಮಯ ಮುಗಿಯಿತು. FDA ಲೆಕ್ಕಪರಿಶೋಧಕ ನಿಮ್ಮ ತಂಡ ಎಲ್ಲ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ ಮುಗಿಸುವ ಮೊದಲು ಬಂದ. ಬ್ಯಾಚ್ BN-2024-3200 ಇನ್ನೂ ಬಗೆಹರಿದಿಲ್ಲ.',
    'end.score_title': 'ಅಂಕ ವಿವರ',
    'end.puzzles_n': 'ಪೂರ್ಣ ಒಗಟುಗಳು ({n} × {pts} ಅಂಕ)',
    'end.time_bonus_n': 'ಸಮಯ ಬೋನಸ್ ({secs}ಸೆ × 2)',
    'end.time_bonus_ot': 'ಸಮಯ ಬೋನಸ್ (ಓವರ್‌ಟೈಮ್ — ಬೋನಸ್ ಇಲ್ಲ)',
    'end.overtime_n': 'ಓವರ್‌ಟೈಮ್ ದಂಡ ({min} ನಿ × −30)',
    'end.wrong_n': 'ತಪ್ಪು ಉತ್ತರ ದಂಡ ({n} × −50)',
    'end.hint_pen': 'ಸಲಹೆ ದಂಡ',
    'end.total_score': 'ಒಟ್ಟು ಅಂಕ:',
    'end.time_taken': 'ತೆಗೆದ ಸಮಯ:',
    'end.demo_note': 'ಡೆಮೋ — ಅಂಕ ಉಳಿಸಲಾಗಿಲ್ಲ',
    'end.lb_link': '📊 ಲೀಡರ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    'tc.header': '🔑 ತಂಡ ಖಚಿತಪಡಿಸುವಿಕೆ ಅಗತ್ಯ',
    'tc.body_html': '<strong>{name}</strong> ಉತ್ತರ ಕಂಡುಕೊಂಡರು. {required} ಸದಸ್ಯರೆಲ್ಲರೂ ಈ ಕೋಡ್ ಹಾಕಬೇಕು:',
    'tc.instruction': 'ನೀವು ಸ್ವೀಕರಿಸಿದ್ದನ್ನು ಖಚಿತಪಡಿಸಲು ಮೇಲಿನ ಕೋಡ್ ಟೈಪ್ ಮಾಡಿ:',
    'tc.input_ph': 'ಕೋಡ್ ಹಾಕಿ…',
    'tc.btn': 'ಖಚಿತಪಡಿಸಿ',
    'modal.default_tag': 'ಗುಣಮಟ್ಟ ನಿಯಂತ್ರಣ',
    'nav.blocked':       'ತಡೆಯಲಾಗಿದೆ.',
    'fb.gmp_ok':           '✓ ಸರಿಯಾದ ಲಾಟ್ ಸಂಖ್ಯೆ! ತಂಡಕ್ಕೆ ತಿಳಿಸಲಾಗುತ್ತಿದೆ — ಎಲ್ಲ ಸದಸ್ಯರ ಖಚಿತಪಡಿಸುವಿಕೆ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ…',
    'fb.gmp_bad':          'ಲಾಟ್ ಸಂಖ್ಯೆ ಗುರುತಿಸಲಿಲ್ಲ. ವಿಶ್ಲೇಷಣಾ ಪ್ರಮಾಣಪತ್ರ ಪರಿಶೀಲಿಸಿ.',
    'fb.inspection_ok':    '✓ ಸರಿ — 4 ದೋಷ ಸಿಕ್ಕಿತು.',
    'fb.inspection_reject_bad': 'ತಪ್ಪು. 4 ದೋಷ ಮತ್ತು Re=4 ಇದ್ದಾಗ ಬ್ಯಾಚ್ ತಿರಸ್ಕರಿಸಬೇಕು.',
    'fb.inspection_type_bad': 'ನಿಖರವಾಗಿ ACCEPT ಅಥವಾ REJECT ಟೈಪ್ ಮಾಡಿ.',
    'fb.inspection_count_bad': 'ನೀವು {n} ಎಣಿಸಿದಿರಿ, ಆದರೆ ತಪಾಸಣೆ ದಾಖಲೆಯೊಂದಿಗೆ ಹೊಂದುವುದಿಲ್ಲ. ಟ್ರೇ ಮತ್ತೆ ಎಚ್ಚರಿಕೆಯಿಂದ ನೋಡಿ.',
    'fb.inspection_nan':   'ದಯವಿಟ್ಟು ಸಂಖ್ಯೆ ಹಾಕಿ.',
    'fb.ncr_bad':          'ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಸಿಗಲಿಲ್ಲ. ಟಿಪ್ಪಣಿ ಪರಿಶೀಲಿಸಿ — ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಸನ್ನಿವೇಶ ವಿವರಣೆಯಲ್ಲಿ ಹೇಳಲಾಗಿದೆ.',
    'fb.cal_bad':          'ತಪ್ಪು. ಸರಿಪಡಿಸುವ ಅಂಶ = ಮಾನದಂಡ − ಓದು = 12.50 − 12.53 = ?',
    'fb.capa_root_ok':     '✓ ಸರಿಯಾದ ಮೂಲ ಕಾರಣ ಗುರುತಿಸಲಾಗಿದೆ.',
    'fb.capa_prev_bad':    'ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ ಅಲ್ಲ. ತಪ್ಪು ಲೂಬ್ರಿಕಂಟ್ ಬಳಕೆ ಅವಕಾಶ ಶಾಶ್ವತವಾಗಿ ತೆಗೆಯುವ ವ್ಯವಸ್ಥಾ ಮಟ್ಟ ಬದಲಾವಣೆ ಯಾವುದು?',
    'fb.capa_root_bad':    'ತಪ್ಪು. ನಿರ್ವಹಣೆ ದಾಖಲೆ ಮತ್ತು SOP ರ್ಯಾಕ್ ಸಂಶೋಧನೆ ಮರುಪರಿಶೀಲಿಸಿ — ಭೌತಿಕ ಸಾಕ್ಷ್ಯ ನಿರ್ದಿಷ್ಟ ವಸ್ತು ಬದಲಾವಣೆ ತೋರಿಸುತ್ತದೆ.',
    'fb.pin_bad':          '❌ PIN ತಪ್ಪಾಗಿದೆ. ದಾಸ್ತಾನಿನ ಬ್ಯಾಚ್ ಬಿಡುಗಡೆ ಪ್ರಮಾಣಪತ್ರ ಪರಿಶೀಲಿಸಿ.',
    'fb.pin_ok':           '✓ ಸರಿಯಾದ PIN! ಬ್ಯಾಚ್ ನಿರ್ಣಯ ಅನುಮೋದಿಸಲು ಎಲ್ಲ ತಂಡ ಸದಸ್ಯರು ಖಚಿತಪಡಿಸಬೇಕು…',
    'fb.motto_prod_bad':   '"ಪ್ರಗತಿ" ಅಂದರೆ ಅಭ್ಯಾಸದಲ್ಲಿ ಏನು ಎಂದು ಯೋಚಿಸಿ. ತಿರಸ್ಕರಣ ಈ ಬಾರಿ ಸಮಸ್ಯೆ ನಿಲ್ಲಿಸುತ್ತದೆ — ಮುಂದಿನ ಬಾರಿ ತಡೆಯುವುದು ಏನು?',
    'fb.motto_qa_bad':     'ಕ್ರಿಯೆ ನಡೆಸಿದ ವ್ಯಕ್ತಿ ಯಾರು ಎಂದು ಯೋಚಿಸಿ. GMP ದಾಖಲಾತಿ ಒಡೆತನ ಹಂತ ನಿರ್ವಹಿಸಿದ ವ್ಯಕ್ತಿಗೆ ನೀಡುತ್ತದೆ.',
    'fb.motto_dis_bad':    'ಸರಿಯಾಗಿ ಇಲ್ಲ. "ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ಪ್ರಗತಿ" ಮತ್ತು "ಪ್ರತಿ ವಿವರದಲ್ಲೂ ಗುಣಮಟ್ಟ" ಕಾಲಾನಂತರದಲ್ಲಿ ಪ್ರಕ್ರಿಯೆ ಹೇಗೆ ನೋಡಿಕೊಳ್ಳಬೇಕು ಎಂದು ಸೂಚಿಸುತ್ತದೆ.',
    'fb.iso15378_1_ok':    '✓ ಸರಿ! ಯಾವುದೇ ಅನಿಯಂತ್ರಿತ ನಿರ್ಣಯ ಮೊದಲು ಪ್ರತ್ಯೇಕ ಮತ್ತು ದಾಖಲಾತಿ ಮಾಡಬೇಕು.',
    'fb.iso15378_2_bad':   'ತಪ್ಪು. GDP ಯ ಬಗ್ಗೆ ಯೋಚಿಸಿ — ಮೂಲ ನಮೂದು ಯಾವಾಗಲೂ ಓದಲು ಸಾಧ್ಯವಾಗಿರಬೇಕು.',
    'fb.iso15378_1_bad':   'ತಪ್ಪು. ISO 15378 ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ QMS ಮಾನದಂಡದ ಮೇಲೆ GMP ಅವಶ್ಯಕತೆ ಸೇರಿಸಲು ವಿನ್ಯಾಸ.',
    'fb.iso9001_1_ok':     '✓ ಸರಿ! ಅಪಾಯ ಆಧಾರಿತ ಚಿಂತನೆ ಅಂದರೆ ಬದಲಾವಣೆ ಕಾರ್ಯವಿಧಾನ ಮಾಡುವ ಮೊದಲೇ ಮೌಲ್ಯಮಾಪನ. ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ ಇಲ್ಲ = ನಿಯಂತ್ರಣ ಇಲ್ಲ.',
    'fb.iso9001_2_bad':    'ತಪ್ಪು. QMS ಮರುಪರಿಶೀಲನೆ ಗುಣಮಟ್ಟ ಘಟನೆ, ಸರಿಪಡಿಸುವ ಕ್ರಮ ಮತ್ತು ವ್ಯವಸ್ಥಾ ಕಾರ್ಯಕ್ಷಮತೆ ಮೌಲ್ಯಮಾಪಿಸಬೇಕು.',
    'fb.iso9001_1_bad':    'ತಪ್ಪು. ಸಮಸ್ಯೆ ಲೆಕ್ಕಪರಿಶೋಧನೆ ಆವರ್ತನ ಅಥವಾ ದಾಖಲೆ ಸಂಗ್ರಹ ಅಲ್ಲ. ಅನನುಮೋದಿತ ವಸ್ತು ಬಳಕೆ ಮೊದಲೇ ತಡೆಯಬಹುದಾಗಿದ್ದ ಯಾವ ಪ್ರಕ್ರಿಯೆ?',
    'modal.waiting_team':  '✓ ಸರಿ! ತಂಡ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ ({done}/{required} ಖಚಿತಪಡಿಸಿದ)…',
    'modal.confirming_team': '✓ ತಂಡ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ ({done}/{required} ಖಚಿತಪಡಿಸಿದ)…',
    'tc.progress':         '✓ {count} / {required} ಸದಸ್ಯರು ಖಚಿತಪಡಿಸಿದ',
    'chat.reconnecting':   'ಮರು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…',
    'chat.placeholder':    'ತಂಡಕ್ಕೆ ಸಂದೇಶ ಕಳಿಸಿ…',
    'log.code_found':      '🔑 ನೀವು "{label}" ಗಾಗಿ ಕೋಡ್ ಕಂಡಿರಿ — {n} ತಂಡ ಸಾಥಿಗಳ ನಿರೀಕ್ಷೆ.',
    'log.code_found_other':'🔑 {name} "{label}" ಉತ್ತರ ಕಂಡರು — ಖಚಿತಪಡಿಸಲು ಕೋಡ್ ಹಾಕಿ!',
    'log.hint_used_other': '💡 {name} {room} ಗಾಗಿ ಸಲಹೆ ಬಳಸಿದರು. ತಂಡಕ್ಕೆ −{time}ಸೆ / −{pts} ಅಂಕ ಕಡಿತ.',
    'log.teammate_done':   '✓ {name} ಪೂರ್ಣಗೊಳಿಸಿದ: {label}',
    'log.item_found_other': '🤝 {name} ಕಂಡರು: {item}',
    'puzzle.label.coa_verified':    'GMP ವಸ್ತು ಪರಿಶೀಲನೆ',
    'puzzle.label.inspection_done': 'AQL ದೃಶ್ಯ ತಪಾಸಣೆ',
    'puzzle.label.ncr_filed':       'ಅಸಂಗತತೆ ವರದಿ',
    'puzzle.label.calibration_done':'ಉಪಕರಣ ಮಾಪನಾಂಶ',
    'puzzle.label.capa_done':       'CAPA ಮೂಲ ಕಾರಣ ವಿಶ್ಲೇಷಣೆ',
    'puzzle.label.batch_retrieved': 'ಬ್ಯಾಚ್ ದಾಖಲೆ ಸಂಗ್ರಹ',
    'puzzle.label.game_won':        'ಅಂತಿಮ ಬ್ಯಾಚ್ ಬಿಡುಗಡೆ',
    'puzzle.label.iso15378_done':   'ISO 15378:2017 ಅನುಸರಣೆ ಪರಿಶೀಲನೆ',
    'puzzle.label.iso9001_done':    'ISO 9001:2015 ನಿರ್ವಹಣಾ ಮರುಪರಿಶೀಲನೆ',
    'puzzle.label.motto_challenge': 'ಗುಣಮಟ್ಟ ಸಪ್ತಾಹ ಧ್ಯೇಯವಾಕ್ಯ ಸವಾಲು (ರವಾನೆ)',
    'puzzle.label.motto_production':'ಗುಣಮಟ್ಟ ಸುಧಾರಣೆ ಧ್ಯೇಯವಾಕ್ಯ (ಉತ್ಪಾದನೆ)',
    'puzzle.label.motto_qaoffice':  'ಗುಣಮಟ್ಟ ಒಡೆತನ ಧ್ಯೇಯವಾಕ್ಯ (QA ಕಚೇರಿ)',
    'login.select_group_placeholder': '— ನಿಮ್ಮ ತಂಡ ಆಯ್ಕೆ ಮಾಡಿ —',
    'login.server_unavailable': 'ಸರ್ವರ್ ಲಭ್ಯವಿಲ್ಲ — ಡೆಮೋ ಮೋಡ್ ಬಳಸಿ',
    'login.server_error': 'ಸರ್ವರ್ ತಲುಪಲಾಗಲಿಲ್ಲ. ಅಂಕ ಇಲ್ಲದೆ ಆಟ ಪರೀಕ್ಷಿಸಲು ಡೆಮೋ ಮೋಡ್ ಬಳಸಿ.',
    'tc.confirmed_waiting': '✓ ಖಚಿತಪಡಿಸಲಾಗಿದೆ! ಉಳಿದ ತಂಡ ಸಾಥಿಗಳ ನಿರೀಕ್ಷೆ…',
    'tc.incorrect':         'ತಪ್ಪು — ಮೇಲೆ ತೋರಿಸಿದಂತೆ ನಿಖರವಾಗಿ ಕೋಡ್ ಹಾಕಿ.',
    'page.title':       'MediSeal ಗುಣಮಟ್ಟ ಸಪ್ತಾಹ — ಎಸ್ಕೇಪ್ ರೂಮ್',
    'login.card_title': 'ಗುಣಮಟ್ಟ ಸಪ್ತಾಹ',
    'login.card_sub':   'ತಂಡ ಲಾಗಿನ್',
    'login.card_motto': 'ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ಪ್ರಗತಿ · ಪ್ರತಿ ವಿವರದಲ್ಲೂ ಗುಣಮಟ್ಟ',
    'login.logged_in_as': 'ಲಾಗಿನ್ ಆಗಿದ್ದೀರಿ: {name}',
    'login.select_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ತಂಡ ಆಯ್ಕೆ ಮಾಡಿ.',
    'login.pin_error':  'ದಯವಿಟ್ಟು PIN ಹಾಕಿ.',
    'login.fail':       'ಲಾಗಿನ್ ವಿಫಲ. PIN ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'login.demo_mode_label': 'ಡೆಮೋ ಮೋಡ್ (ನಿರ್ವಾಹಕ)',
    'login.demo_start_btn':  'ಲೆಕ್ಕಪರಿಶೋಧನೆ ಅನುಕರಣೆ ಪ್ರಾರಂಭಿಸಿ',
    'login.admin_pw_wrong':  'ತಪ್ಪು ನಿರ್ವಾಹಕ ಪಾಸ್‌ವರ್ಡ್.',
    'start.btn_waiting_text': "✓ ನಾನು ತಯಾರು — ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ…",
    'start.card_motto': 'ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ಪ್ರಗತಿ · ಪ್ರತಿ ವಿವರದಲ್ಲೂ ಗುಣಮಟ್ಟ',
    'lb.h2':            '📊 ಲೀಡರ್‌ಬೋರ್ಡ್',
    'lb.admin_pw':      'ನಿರ್ವಾಹಕ ಪಾಸ್‌ವರ್ಡ್',
    'lb.admin_pw_ph':   'ನಿರ್ವಾಹಕ ಪಾಸ್‌ವರ್ಡ್ ಹಾಕಿ',
    'lb.view_btn':      'ಲೀಡರ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    'lb.close_btn':     'ಮುಚ್ಚಿ',
    'lb.completed_groups': 'ಪೂರ್ಣ ತಂಡಗಳು — ಅಂಕ ಆಧಾರ ಶ್ರೇಣಿ',
    'lb.close_btn2':    'ಮುಚ್ಚಿ',
    'lb.empty':         'ಯಾವ ತಂಡವೂ ಇನ್ನೂ ಆಟ ಮುಗಿಸಿಲ್ಲ.',
    'lb.col_group':     'ತಂಡ',
    'lb.col_score':     'ಅಂಕ',
    'lb.col_puzzles':   'ಒಗಟು',
    'lb.col_time_left': 'ಉಳಿದ ಸಮಯ',
    'lb.col_wrong':     'ತಪ್ಪು',
    'lb.col_finished':  'ಮುಗಿಸಿದ',
    'lb.wrong_pw':      'ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್.',
    'already.title':    'ಈಗಾಗಲೇ ಆಡಿದ್ದೀರಿ',
    'already.sub':      'ನಿಮ್ಮ ತಂಡ ಆಟ ಆಡಿದೆ',
    'already.body':     'ನಿಮ್ಮ ತಂಡ ಈಗಾಗಲೇ ಗುಣಮಟ್ಟ ಸಪ್ತಾಹ ಎಸ್ಕೇಪ್ ರೂಮ್ ಆಡಿ ಮುಗಿಸಿದೆ.<br>ಪ್ರತಿ ತಂಡ ಒಮ್ಮೆ ಮಾತ್ರ ಆಡಬಹುದು. ನಿಮ್ಮ ಅಂಕ ನೋಡಲು ಲೀಡರ್‌ಬೋರ್ಡ್ ಪರಿಶೀಲಿಸಿ!',
    'already.lb_btn':   '📊 ಲೀಡರ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    'end.lb_btn':       '📊 ಲೀಡರ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    'hint.penalty_log': '⚠️ ಸಲಹೆ ದಂಡ ಅನ್ವಯ: −{time}ಸೆ ಮತ್ತು −{pts} ಅಂಕ.',
    'nav.here':     ' — ನೀವಿಲ್ಲಿದ್ದೀರಿ',
    'nav.visited':  ' — ಭೇಟಿ ಮಾಡಿದ',
    'nav.unlocked': ' — ತೆರೆದಿದೆ',
    'nav.locked':   ' — ಲಾಕ್ ಆಗಿದೆ',
    'side.no_entries_html': 'ಇನ್ನೂ ಯಾವ ನಮೂದು ಇಲ್ಲ.',
    'room.badge.receiving':  'ಪ್ರದೇಶ 01 — ಸ್ವೀಕರಿಸುವ ಡಾಕ್',
    'room.badge.production': 'ಪ್ರದೇಶ 02 — ಉತ್ಪಾದನಾ ಲೈನ್',
    'room.badge.qclab':      'ಪ್ರದೇಶ 03 — QC ಪ್ರಯೋಗಾಲಯ',
    'room.badge.qaoffice':   'ಪ್ರದೇಶ 04 — QA / ಅನುಸರಣೆ',
    'room.badge.dispatch':   'ಪ್ರದೇಶ 05 — ರವಾನೆ / ಬಿಡುಗಡೆ',
    'room.desc.receiving':  'ಒಳಬರುವ ಗುಣಮಟ್ಟ ನಿಯಂತ್ರಣಕ್ಕಾಗಿ ಕಚ್ಚಾ ವಸ್ತು ಇಲ್ಲಿ ಬರುತ್ತದೆ. GMP ಅಡಿ, ಉತ್ಪಾದನೆಗೆ ಬಿಡುಗಡೆ ಮಾಡುವ ಮೊದಲು ಪ್ರತಿ ಒಳಬರುವ ಬ್ಯಾಚ್ ವಿಶ್ಲೇಷಣಾ ಪ್ರಮಾಣಪತ್ರ ಪರಿಶೀಲಿಸಬೇಕು. ರಬ್ಬರ್ ಸಂಯೋಜನೆ ಪ್ಯಾಲೆಟ್ ಮೇಲೆ ಕೆಂಪು HOLD ದೀಪ ಮಿನುಗುತ್ತಿದೆ. GMP ಟರ್ಮಿನಲ್ ಓದುತ್ತಿದೆ: "ವಸ್ತು HOLD ನಲ್ಲಿದೆ — ಪರಿಶೀಲನೆ ಅಗತ್ಯ."',
    'room.desc.production': 'ಇನ್ಸುಲಿನ್ ವಯಲ್ ಮತ್ತು ಪ್ರಿಫಿಲ್ಡ್ ಸಿರಿಂಜ್‌ಗಳಿಗಾಗಿ ರಬ್ಬರ್ ಪ್ಲಂಜರ್‌ಗಳ ಮುಖ್ಯ ಅಚ್ಚು ಮತ್ತು ಜೋಡಣಾ ಲೈನ್. ನಿಲ್ದಾಣ 3 ರಲ್ಲಿ ಲೈನ್ ನಿಂತಿದೆ — ಅಂಬರ್ ದೀಪ ಮಿನುಗುತ್ತಿದೆ. ದೃಶ್ಯ ತಪಾಸಣೆ ಲೈಟ್ ಬಾಕ್ಸ್ ನಿಲ್ದಾಣ ಸ್ಥಾಪಿಸಲಾಗಿದೆ. AQL ಮಾದರಿ ಚಾರ್ಟ್ ಅಕ್ಕಪಕ್ಕ ಜೋಡಿಸಲಾಗಿದೆ.',
    'room.desc.qclab':      'QC ಪ್ರಯೋಗಾಲಯ IPA ಮತ್ತು ಮಾಪನಾಂಶ ದ್ರವ ವಾಸನೆ. ಆಯಾಮ ಮಾಪಕ, ಕಣ ಎಣಿಕೆ ಮತ್ತು ಕ್ರಿಮಿ ಪರೀಕ್ಷಾ ಉಪಕರಣ ಮೇಜಿನ ಮೇಲೆ ಸಾಲಾಗಿ. ಮೂಲೆಯ ಮೈಕ್ರೋಮೀಟರ್ ನಿಲ್ದಾಣ ಹಳದಿ "ಮಾಪನಾಂಶ ಮೀಯಾದಿ ಮೀರಿದೆ — ಬಳಸಬೇಡಿ" ಸ್ಟಿಕ್ಕರ್ ಹೊಂದಿದೆ.',
    'room.desc.qaoffice':   'ಗುಣಮಟ್ಟ ಕಾರ್ಯಾಚರಣೆ ಕೇಂದ್ರ. ISO 13485 ಕ್ಲಾಸ್ ಲೇಬಲ್ ಫೈಲಿಂಗ್ ಕ್ಯಾಬಿನೆಟ್ ಉದ್ದಕ್ಕೂ. CAPA ವರ್ಕ್‌ಸ್ಟೇಶನ್ ತೋರಿಸುತ್ತದೆ: "ಅಸಂಗತತೆ #NCR-0892 — ಮೂಲ ಕಾರಣ ವಿಶ್ಲೇಷಣೆ ಬಾಕಿ." ನಿರ್ವಹಣೆ ದಾಖಲೆ ಬದಿ ಮೇಜಿನ ಮೇಲೆ ತೆರೆದಿದೆ.',
    'room.desc.dispatch':   'ಉತ್ಪನ್ನ ಕಟ್ಟಡ ಬಿಡುವ ಮೊದಲು ಅಂತಿಮ ತಪಾಸಣಾ ಕೇಂದ್ರ. ಕ್ವಾರಂಟೈನ್ ಪಂಜರ ಬ್ಯಾಚ್ BN-2024-3200 ಹಿಡಿದಿದೆ — QA ಅನುಮೋದನೆ ಬಾಕಿ ತಾಳ ಜಡಿದಿದೆ. ಬ್ಯಾಚ್ ಬಿಡುಗಡೆ ಟರ್ಮಿನಲ್ ಅಂಬರ್ ಹೊಳೆಯುತ್ತಿದೆ.',
    'item.coa.name':         'ವಿಶ್ಲೇಷಣಾ ಪ್ರಮಾಣಪತ್ರ',
    'item.coa.desc':         'CoA — ರಬ್ಬರ್ ಸಂಯೋಜನೆ RC-500 | ಲಾಟ್: RM-4471 | ಸಪ್ಲೈಯರ್: Kautschuk GmbH | ಸ್ಥಿತಿ: GMP ಪರಿಶೀಲನೆ ಬಾಕಿ. ಎಲ್ಲ ಒಳಬರುವ ವಸ್ತು GMP ಪ್ರಕಾರ ಪರಿಶೀಲನೆ ಆಗಬೇಕು.',
    'item.aql_table.name':   'AQL ಮಾದರಿ ಚಾರ್ಟ್',
    'item.aql_table.desc':   'ISO 2859-1 AQL ಕೋಷ್ಟಕ: ಲಾಟ್ ಗಾತ್ರ 3,200 | ತಪಾಸಣಾ ಮಟ್ಟ II | AQL 1.0 → ಮಾದರಿ ಕೋಡ್ K → ಮಾದರಿ ಗಾತ್ರ: 125 | ಸ್ವೀಕರಿಸು ≤ 3 | ತಿರಸ್ಕರಿಸು ≥ 4.',
    'item.ncr_form.name':    'ಅಸಂಗತತೆ ವರದಿ',
    'item.ncr_form.desc':    'NCR-0892: ಬ್ಯಾಚ್ BN-2024-3200 — 125 ರ ಮಾದರಿಯಲ್ಲಿ 4 ದೋಷ. Re=4 ಮೀರಿದೆ. ಬ್ಯಾಚ್ ನಿರ್ಣಯ: ತಿರಸ್ಕೃತ. SOP-QC-015 ಪ್ರಕಾರ ಎತ್ತಲಾಗಿದೆ.',
    'item.cal_ref.name':     'ಮಾಪನಾಂಶ ಉಲ್ಲೇಖ',
    'item.cal_ref.desc':     'ಪ್ರಮಾಣೀಕೃತ ಮಾಪ ಬ್ಲಾಕ್: 12.50 mm (±0.001 mm). ಪ್ರಮಾಣಪತ್ರ ಸಂ. CAL-7734. ISO/IEC 17025 ಪ್ರಕಾರ ರಾಷ್ಟ್ರೀಯ ಮಾನದಂಡಕ್ಕೆ ಪತ್ತೆ ಸಾಧ್ಯ. ಉಪಕರಣ ನಿಖರತೆ ಪರಿಶೀಲಿಸಲು ಬಳಸಿ.',
    'item.maint_log.name':   'ನಿರ್ವಹಣೆ ದಾಖಲೆ',
    'item.maint_log.desc':   'ದಾಖಲೆ ನಮೂದು 14/03/24 — ನಿಲ್ದಾಣ 3 ಅಚ್ಚು ಉಪಕರಣ: ಬಿಡುಗಡೆ ಲೂಬ್ರಿಕಂಟ್ Grade B-7 (ಸಿಂಥೆಟಿಕ್) ಗೆ ಬದಲಾಯಿಸಲಾಯಿತು. SOP-MAINT-009 ಪ್ರಕಾರ ಸರಿಯಾದ ದರ್ಜೆ Grade A-3 (food-grade silicone). ವಿಚಲನ ನಮೂನೆ ಎತ್ತಿಲ್ಲ!',
    'item.capa_report.name': 'ಪೂರ್ಣ CAPA ವರದಿ',
    'item.capa_report.desc': 'CAPA-0112: ಮೂಲ ಕಾರಣ — ಅಚ್ಚು ಉಪಕರಣದ ಮೇಲೆ ತಪ್ಪು ಲೂಬ್ರಿಕಂಟ್ (B-7 ಬದಲು A-3). ತಕ್ಷಣ ಕ್ರಮ: ಉತ್ಪಾದನಾ ತಡೆ. ತಡೆ: SOP ನವೀಕರಣ + ಮರು ತರಬೇತಿ. ISO 13485 §8.5.',
    'item.batch_cert.name':  'ಬ್ಯಾಚ್ ಬಿಡುಗಡೆ ಪ್ರಮಾಣಪತ್ರ',
    'item.batch_cert.desc':  'ಬ್ಯಾಚ್ BN-2024-3200 | ನಿರ್ಣಯ: ತಿರಸ್ಕರಿಸಿ ಮತ್ತು ಕ್ವಾರಂಟೈನ್ | ಕಾರಣ: NCR-0892 / CAPA-0112. QA ಅನುಮತಿ PIN: 4471. ISO 13485 §8.3 ಅಡಿ ಸಹಿ.',
    'item.stopper_spec.name':'ISO 15378 ಪ್ಯಾಕೇಜಿಂಗ್ ವಿಶೇಷಣ',
    'item.stopper_spec.desc':'ರಬ್ಬರ್ ಸ್ಟಾಪರ್ ವಿಶೇಷಣ — ISO 15378:2017 ಔಷಧೀಯ ಉತ್ಪನ್ನಗಳಿಗಾಗಿ ಪ್ರಾಥಮಿಕ ಪ್ಯಾಕೇಜಿಂಗ್ ವಸ್ತುಗಳು. ಸಪ್ಲೈಯರ್: Kautschuk GmbH. ವಸ್ತು: ಬ್ರೋಮೋಬ್ಯುಟಿಲ್ ರಬ್ಬರ್ ಸಂಯೋಜನೆ.',
    'item.iso9001_cert.name':'ISO 9001:2015 ಪ್ರಮಾಣಪತ್ರ',
    'item.iso9001_cert.desc':'ISO 9001:2015 ಗುಣಮಟ್ಟ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ ಪ್ರಮಾಣಪತ್ರ — MediSeal Manufacturing Ltd. ವ್ಯಾಪ್ತಿ: ಔಷಧೀಯ ಸಾಧನಗಳಿಗೆ ರಬ್ಬರ್ ಪ್ಲಂಜರ್ ಮತ್ತು ಮುಚ್ಚಳ ವಿನ್ಯಾಸ, ತಯಾರಿಕೆ ಮತ್ತು ಪೂರೈಕೆ.',
    'item.selected_prefix':  'ಆಯ್ಕೆಯಾಗಿದೆ: ',
    'note.coa_found':    'CoA ಸಿಕ್ಕಿತು — ಲಾಟ್ <strong>RM-4471</strong>, ಸಪ್ಲೈಯರ್ Kautschuk GmbH. ವಸ್ತು ಬಿಡುಗಡೆಗೆ GMP ಟರ್ಮಿನಲ್‌ನಲ್ಲಿ ಹಾಕಬೇಕು.',
    'note.aql_chart':    'AQL ಚಾರ್ಟ್: ಲಾಟ್ 3,200 | ಮಟ್ಟ II | AQL 1.0 → ಮಾದರಿ ಗಾತ್ರ <strong>125</strong> | Ac=3, Re=4',
    'note.station3_log': 'ನಿಲ್ದಾಣ 3 ಉಪಕರಣ ದಾಖಲೆ: ಮೈಕ್ರೋಮೀಟರ್ SN-7734 ಬ್ಯಾಚ್ BN-2024-3200 ನಲ್ಲಿ <strong>+0.03 mm</strong> ವ್ಯವಸ್ಥಿತ ವ್ಯತ್ಯಾಸ ದಾಖಲಿಸಿತು. ಉಲ್ಲೇಖ ಪ್ಲಗ್ = 12.50 mm; ಉಪಕರಣ 12.53 mm ತೋರಿಸಿತು.',
    'note.cal_ref':      'ಮಾಪನಾಂಶ ಉಲ್ಲೇಖ: ಪ್ರಮಾಣೀಕೃತ ಮಾಪ ಬ್ಲಾಕ್ = <strong>12.50 mm</strong> (±0.001 mm). ಮೈಕ್ರೋಮೀಟರ್ SN-7734 ಪರಿಶೀಲಿಸಲು ಬಳಸಿ.',
    'note.sop_rack':     'SOP ರ್ಯಾಕ್: SOP-QC-015 (ದೃಶ್ಯ ತಪಾಸಣೆ), SOP-QC-022 (AQL ಮಾದರಿ), SOP-MAINT-009 (ಅಚ್ಚು ಲೂಬ್ರಿಕಂಟ್ — Grade A-3 ಮಾತ್ರ)',
    'note.equip_log':    'ಉಪಕರಣ ದಾಖಲೆ — ಮೈಕ್ರೋಮೀಟರ್ SN-7734: 90 ದಿನ ಮೀಯಾದಿ ಮೀರಿದೆ. ಐತಿಹಾಸಿಕ ವ್ಯತ್ಯಾಸ ದತ್ತಾಂಶ <strong>ನಿಲ್ದಾಣ 3 ಉಪಕರಣ ದಾಖಲೆ</strong> (ಉತ್ಪಾದನಾ ಪ್ರದೇಶ) ನಲ್ಲಿ.',
    'note.maint_log':    'ನಿರ್ವಹಣೆ ದಾಖಲೆ — ನಿಲ್ದಾಣ 3: ಲೂಬ್ರಿಕಂಟ್ <strong>Grade B-7</strong> ಗೆ ಬದಲಾಯಿಸಲಾಗಿದೆ (ತಪ್ಪು). ಸರಿಯಾದ ದರ್ಜೆ: <strong>Grade A-3</strong>. ವಿಚಲನ ಎತ್ತಿಲ್ಲ!',
    'note.iso13485':     'ISO 13485 ಮುಖ್ಯ ಕ್ಲಾಸ್: §4 QMS | §6 ಸಂಪನ್ಮೂಲ | §7 ಉತ್ಪನ್ನ ಸಾಕ್ಷಾತ್ಕಾರ | <strong>§8 ಅಳತೆ, ವಿಶ್ಲೇಷಣೆ &amp; ಸುಧಾರಣೆ</strong> — §8.3 ಅಸಂಗತ ಉತ್ಪನ್ನ, §8.5.2 ಸರಿಪಡಿಸುವ ಕ್ರಮ, §8.5.3 ತಡೆ ಕ್ರಮ',
    'note.batch_cert':   'ಬ್ಯಾಚ್ ಬಿಡುಗಡೆ ಪ್ರಮಾಣಪತ್ರ — ಅನುಮತಿ PIN: <strong>4471</strong>. ನಿರ್ಣಯ: ತಿರಸ್ಕರಿಸಿ &amp; ಕ್ವಾರಂಟೈನ್.',
    'note.iso15378':     'ISO 15378:2017 ಪ್ಯಾಕೇಜಿಂಗ್ ವಿಶೇಷಣ: Kautschuk GmbH ರಬ್ಬರ್ ಸ್ಟಾಪರ್. ಮಾನದಂಡ <strong>ISO 9001:2015 + GMP</strong> ಸಂಯೋಜಿಸುತ್ತದೆ. ಮುಖ್ಯ ಉಲ್ಲೇಖ: <strong>ಕ್ಲಾಸ್ 8.7</strong> — ಅಸಂಗತ ಉತ್ಪಾದನೆ ನಿಯಂತ್ರಣ.',
    'note.iso9001_cert': 'ISO 9001:2015 ಪ್ರಮಾಣಪತ್ರ — MediSeal. ಗುಣಮಟ್ಟ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ. ಪ್ರಮಾಣೀಕೃತ ವ್ಯಾಪ್ತಿ ಔಷಧ ಪ್ಯಾಕೇಜಿಂಗ್ ವಸ್ತು ವಿನ್ಯಾಸ, ತಯಾರಿಕೆ ಮತ್ತು ವಿತರಣೆ.',
    'pts':                'ಅಂಕ',
    'lobby.ready_status': '✓ ತಯಾರು: {count} / {total}  ({names})',
    'members.online':     '{n} ಆನ್‌ಲೈನ್',
    'lobby.connected':    '{count}/5 ಸಂಪರ್ಕಿತ',
    'login.group_size':         'ನಿಮ್ಮ ತಂಡದಲ್ಲಿ ಎಷ್ಟು ಜನ?',
    'login.group_size_ph':      '— ತಂಡ ಗಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ —',
    'login.group_size_3':       '3 ಆಟಗಾರರು',
    'login.group_size_4':       '4 ಆಟಗಾರರು',
    'login.group_size_5':       '5 ಆಟಗಾರರು',
    'login.group_size_error':   'ದಯವಿಟ್ಟು ತಂಡ ಗಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ (3, 4, ಅಥವಾ 5).',
    'login.size_mismatch':      'ಈ ತಂಡ ಈಗಾಗಲೇ {required} ಆಟಗಾರರನ್ನು ನಿಗದಿಪಡಿಸಿದೆ.',
    'login.group_full':         'ಈ ತಂಡ ತುಂಬಿದೆ ({required} ಆಟಗಾರರು ಸಂಪರ್ಕಿತರಾಗಿದ್ದಾರೆ).',
    'login.roster_locked':      'ಈ ಸೆಷನ್ ಪ್ರಾರಂಭವಾಗಿದೆ. ಮೂಲ ತಂಡ ಸದಸ್ಯರು ಮಾತ್ರ ಮರು ಸೇರಬಹುದು.',
    'login.permanently_locked': 'ಈ ತಂಡ ಈಗಾಗಲೇ ಆಟ ಮುಗಿಸಿದೆ. ಫಲಿತಾಂಶ ಅಂತಿಮ.',
    'lobby.need_exact':         '{needed} ಹೆಚ್ಚು ಆಟಗಾರ(ರ) ಸೇರಲು ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ.',
    'lobby.connected_of':       'ಸಂಪರ್ಕಿತ',
    'lobby.all_ready':          'ಎಲ್ಲ ಆಟಗಾರರು ಸಂಪರ್ಕಿತ! ಪ್ರಾರಂಭಿಸಲು ಎಲ್ಲರೂ ತಯಾರು ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'lobby.wrong_count':        'ನಿಖರವಾಗಿ {required} ಆಟಗಾರರು ಬೇಕು. ಪ್ರಸ್ತುತ {online} ಸಂಪರ್ಕಿತ.',
    'lobby.too_many':           'ಹೆಚ್ಚು ಆಟಗಾರರಿದ್ದಾರೆ. {required} ಬೇಕಾಗಿತ್ತು, {online} ಇದ್ದಾರೆ.',
    'pause.title':              'ಆಟ ವಿರಾಮ',
    'pause.body':               '{name} ಸಂಪರ್ಕ ಕಡಿದರು. ಈ ಸೆಷನ್‌ಗೆ {total} ಆಟಗಾರರು ಅಗತ್ಯ. ಎಲ್ಲರೂ ಮರಳುವವರೆಗೆ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ.',
    'pause.waiting_for':        'ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ: {names}',
    'pause.resumed':            '✓ ಎಲ್ಲ ಆಟಗಾರರು ಮರಳಿದ್ದಾರೆ! ಆಟ ಮುಂದುವರಿಯುತ್ತಿದೆ…',
    'msg.your_task_done':       '✓ ನೀವು ಈ ಕಾರ್ಯ ಮುಗಿಸಿದ್ದೀರಿ. ತಂಡ ಸಾಥಿಗಳ ನಿರೀಕ್ಷೆ…',
    'msg.team_progress':        '{done} / {total} ಆಟಗಾರರು ಈ ಕಾರ್ಯ ಮುಗಿಸಿದ್ದಾರೆ.',
    'msg.all_players_done':     '✓ ಎಲ್ಲ ಆಟಗಾರರು ಮುಗಿಸಿದ್ದಾರೆ: {label}',
    'log.all_players_done':     '✓ ಎಲ್ಲ ಆಟಗಾರರು ಮುಗಿಸಿದ್ದಾರೆ: {label}',
    'msg.missing_tasks':        'ನೀವು ಈ ಕೋಣೆಯಲ್ಲಿ ಏನನ್ನೋ ಮುಗಿಸಿಲ್ಲ.',
    'msg.incomplete_tasks':     'ಮುಂದೆ ಹೋಗುವ ಮೊದಲು ಎಲ್ಲ ಅಗತ್ಯ ಕ್ರಿಯೆ ಪೂರ್ಣಗೊಳಿಸಿ.',
    'msg.pin_incomplete':       'ಅಂತಿಮ PIN ಸರಿಯಾಗಿದೆ, ಆದರೆ ನಿಮ್ಮ ತಂಡ ಎಲ್ಲ ಅಗತ್ಯ ಕಾರ್ಯ ಮುಗಿಸಿಲ್ಲ.',
    'rules.english_answers':    'ಕೆಲ ಉತ್ತರ ತೋರಿಸಿದಂತೆ ನಿಖರವಾಗಿ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಟೈಪ್ ಮಾಡಬೇಕು (ಉದಾ. ಲಾಟ್ ಸಂಖ್ಯೆ, ACCEPT/REJECT). ಕೇಸ್-ಸೆನ್ಸಿಟಿವ್ ಕ್ಷೇತ್ರ ಪ್ರಶ್ನೆಯಲ್ಲಿ ಗುರುತಿಸಲಾಗಿರುತ್ತದೆ.',
    'hq.found_badge':           '★ ಬೋನಸ್ ಪ್ರಶ್ನೆ',
    'hq.found_badge_done':      '★ ಬೋನಸ್ (ಉತ್ತರಿಸಿದ)',
    'hq.intro':                 'ನೀವು ಗುಪ್ತ ಬೋನಸ್ ಪ್ರಶ್ನೆ ಕಂಡಿರಿ! ಇದು ಐಚ್ಛಿಕ — ಸರಿ ಉತ್ತರ ನಿಮ್ಮ ತಂಡಕ್ಕೆ +20 ಬೋನಸ್ ಅಂಕ. ನಿಮ್ಮ ತಂಡ ಒಂದೇ ಒಮ್ಮೆ ಪ್ರಯತ್ನ.',
    'hq.answered_correct':      '✓ ಸರಿ! ನಿಮ್ಮ ತಂಡಕ್ಕೆ +20 ಬೋನಸ್ ಅಂಕ!',
    'hq.answered_wrong':        '✗ ಅಲ್ಲ — ಅಂಕ ಇಲ್ಲ, ತಪ್ಪು ಉತ್ತರ ದಂಡ ಇಲ್ಲ.',
    'hq.result_correct':        '{who} ಇದನ್ನು ಸರಿಯಾಗಿ ಉತ್ತರಿಸಿದ್ದಾರೆ. ಸರಿಯಾದ ಉತ್ತರ: {correct}',
    'hq.result_wrong':          '{who} ತಪ್ಪಾಗಿ ಉತ್ತರಿಸಿದ್ದಾರೆ. ಸರಿಯಾದ ಉತ್ತರ: {correct}',
    'hq.submitting':            'ನಿಮ್ಮ ಉತ್ತರ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ…',
    'hq.answered_correct_log':  '{who} ಬೋನಸ್ ಪ್ರಶ್ನೆ ಸರಿಯಾಗಿ ಉತ್ತರಿಸಿದ! +{pts} ಅಂಕ',
    'hq.answered_wrong_log':    '{who} ಬೋನಸ್ ಪ್ರಶ್ನೆ ಉತ್ತರಿಸಿದ — ಅಂಕ ನೀಡಲಾಗಿಲ್ಲ.',
    'end.hidden_bonus':         'ಬೋನಸ್ ಪ್ರಶ್ನೆ ({found} ಕಂಡ, {correct} ಸರಿ)',
    'hq.hq_receiving_1.title':  'ಆಹಾರ ಗುಣಮಟ್ಟ: ದೈನಂದಿನ ಪರೀಕ್ಷೆ',
    'hq.hq_receiving_1.body':   'ಮೊಟ್ಟೆ ಬೇಯಿಸುವ ಮೊದಲು ಹಾಳಾಗಿದೆಯೇ ಎಂದು ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಹೇಗೆ ಪರಿಶೀಲಿಸಬಹುದು?',
    'hq.hq_receiving_1.a':      'ತಣ್ಣೀರಲ್ಲಿ ಇಡಿ — ತೇಲುವ ಮೊಟ್ಟೆ ಹಾಳಾಗಿರಬಹುದು.',
    'hq.hq_receiving_1.b':      'ಒಡೆದು ತಿರುಳಿನ ಬಣ್ಣ ನೋಡಿ.',
    'hq.hq_receiving_1.c':      'ಮೆಲ್ಲಗೆ ಅಲ್ಲಾಡಿಸಿ — ಹಾಳಾದ ಮೊಟ್ಟೆ ಭಾರ ಅನಿಸುತ್ತದೆ.',
    'hq.hq_receiving_1.d':      'ಒಡೆಯುವ ಮೊದಲು ಚಿಪ್ಪಿನ ಹೊರಗೆ ವಾಸನೆ ಮೂಸಿ.',
    'hq.hq_receiving_2.title':  'ವಾಯು ಗುಣಮಟ್ಟ: ಬಣ್ಣ ಸಂಕೇತ',
    'hq.hq_receiving_2.body':   'ಹೆಚ್ಚಿನ ವಾಯು ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕದಲ್ಲಿ \'ಉತ್ತಮ\' ವಾಯು ಗುಣಮಟ್ಟ ಸಾಮಾನ್ಯವಾಗಿ ಯಾವ ಬಣ್ಣ?',
    'hq.hq_receiving_2.a':      'ಕೆಂಪು — ಹೆಚ್ಚಿನ ಮಾಲಿನ್ಯ ಮಟ್ಟ ಸೂಚಿಸುತ್ತದೆ.',
    'hq.hq_receiving_2.b':      'ಹಳದಿ — ಮಧ್ಯಮ ವಾಯು ಗುಣಮಟ್ಟ ಇದೆ.',
    'hq.hq_receiving_2.c':      'ಹಸಿರು — ಅತ್ಯಂತ ಕಡಿಮೆ ಮಾಲಿನ್ಯ ಅಳತೆ ಸೂಚಿಸುತ್ತದೆ.',
    'hq.hq_receiving_2.d':      'ನೇರಳೆ — ಅತ್ಯಂತ ಶುದ್ಧ ವಾಯು ಗುಣಮಟ್ಟ ಸೂಚಿಸುತ್ತದೆ.',
    'hq.hq_production_1.title': 'ನೀರಿನ ಗುಣಮಟ್ಟ: ಸುರಕ್ಷಿತತೆ ಚಿಹ್ನೆ',
    'hq.hq_production_1.body':  'ನಲ್ಲಿ ನೀರು ಕುಡಿಯಲು ಸುರಕ್ಷಿತ ಅಲ್ಲ ಎಂಬ ಒಂದು ಸಾಮಾನ್ಯ ಚಿಹ್ನೆ ಯಾವುದು?',
    'hq.hq_production_1.a':     'ನೀರು ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಸ್ವಲ್ಪ ತಂಪಾಗಿ ಕಾಣಿಸುತ್ತದೆ.',
    'hq.hq_production_1.b':     'ಸುರಿದ ನಂತರ ನೀರು ಅಸಾಮಾನ್ಯ ವಾಸನೆ ಬರುತ್ತದೆ.',
    'hq.hq_production_1.c':     'ನೀರು ನಲ್ಲಿಯಿಂದ ಬರಲು ಹೆಚ್ಚು ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.',
    'hq.hq_production_1.d':     'ನೀರು ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಸ್ವಲ್ಪ ಬಿಸಿಯಾಗಿ ಅನಿಸುತ್ತದೆ.',
    'hq.hq_production_2.title': 'ತಯಾರಿಕೆ: ಬಾರ್‌ಕೋಡ್ ಅನುಕೂಲ',
    'hq.hq_production_2.body':  'ಬಾರ್‌ಕೋಡ್ ಮುಖ್ಯವಾಗಿ ಕಂಪನಿ ಯಾವುದನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ?',
    'hq.hq_production_2.a':     'ಉತ್ಪನ್ನ ನೋಟ ಮತ್ತು ಪ್ಯಾಕೇಜಿಂಗ್ ವಿನ್ಯಾಸ ಗುಣಮಟ್ಟ.',
    'hq.hq_production_2.b':     'ಪೂರೈಕೆ ಸರಪಳಿ ವ್ಯವಸ್ಥೆಯಲ್ಲಿ ದಾಸ್ತಾನು ಟ್ರ್ಯಾಕಿಂಗ್ ನಿಖರತೆ.',
    'hq.hq_production_2.c':     'ಗ್ರಾಹಕ ತೃಪ್ತಿ ರೇಟಿಂಗ್ ಮತ್ತು ಬ್ರಾಂಡ್ ನಿಷ್ಠೆ.',
    'hq.hq_production_2.d':     'ನೌಕರ ಉತ್ಪಾದಕತೆ ಮತ್ತು ಕಾರ್ಯಸ್ಥಳ ಸುರಕ್ಷತೆ ಅಂಕ.',
    'hq.hq_qclab_1.title':      'ಪರಿಸರ ಗುಣಮಟ್ಟ: ನಗರ ಮರಗಳು',
    'hq.hq_qclab_1.body':       'ನಗರ ಪರಿಸರ ಗುಣಮಟ್ಟ ಸುಧಾರಿಸಲು ಮರಗಳು ಏಕೆ ಮುಖ್ಯ?',
    'hq.hq_qclab_1.a':          'ಮರಗಳು ಮುಖ್ಯವಾಗಿ ಕಟ್ಟಡ ತಾಪಮಾನ ಕಡಿಮೆ ಮಾಡಲು ನೆರಳು ನೀಡುತ್ತವೆ.',
    'hq.hq_qclab_1.b':          'ಮರಗಳು ಶಬ್ದ ಕಡಿಮೆ ಮಾಡಿ ಗಾಳಿಯ ಮಾಲಿನ್ಯಕಾರಕ ಶೋಧಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ.',
    'hq.hq_qclab_1.c':          'ಮರಗಳು ಪ್ರಾಥಮಿಕವಾಗಿ ನಗರ ಪ್ರದೇಶದ ಆಸ್ತಿ ಮೌಲ್ಯ ಹೆಚ್ಚಿಸುತ್ತವೆ.',
    'hq.hq_qclab_1.d':          'ಮರಗಳು ಮುಖ್ಯವಾಗಿ ವನ್ಯಜೀವಿ ಆವಾಸಸ್ಥಾನ ರಚನೆಗೆ ಮುಖ್ಯ.',
    'hq.hq_qclab_2.title':      'ಉತ್ಪನ್ನ ಗುಣಮಟ್ಟ: ಶಿಪ್ಪಿಂಗ್ ಮೊದಲು ತಪಾಸಣೆ',
    'hq.hq_qclab_2.body':       'ಅನೇಕ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಉತ್ಪನ್ನ ಶಿಪ್ಪಿಂಗ್ ಮೊದಲು ಗುಣಮಟ್ಟ ನಿಯಂತ್ರಣ ತಪಾಸಣೆ ಏಕೆ ಮಾಡುತ್ತವೆ?',
    'hq.hq_qclab_2.a':          'ಗಮ್ಯಸ್ಥಾನ ದೇಶದ ಕಸ್ಟಮ್ಸ್ ನಿಯಮ ಪಾಲಿಸಲು.',
    'hq.hq_qclab_2.b':          'ಅಂತಿಮ ಗ್ರಾಹಕರನ್ನು ತಲುಪುವ ಮೊದಲು ದೋಷ ಗುರುತಿಸಲು.',
    'hq.hq_qclab_2.c':          'ವಿಮಾ ಉದ್ದೇಶಕ್ಕೆ ಶಿಪ್‌ಮೆಂಟ್ ಒಟ್ಟು ತೂಕ ಹೆಚ್ಚಿಸಲು.',
    'hq.hq_qclab_2.d':          'ಖರೀದಿ ನಂತರ ಉತ್ಪನ್ನ ವಾರಂಟಿ ಅಗತ್ಯ ಕಡಿಮೆ ಮಾಡಲು.',
    'hq.hq_qaoffice_1.title':   'ಗುಣಮಟ್ಟ ವ್ಯವಸ್ಥೆ: ಮೀಯಾದಿ ತಾರೀಖು',
    'hq.hq_qaoffice_1.body':    'ಪ್ಯಾಕ್ ಮಾಡಿದ ಆಹಾರ ಉತ್ಪನ್ನದ ಮೀಯಾದಿ ತಾರೀಖಿನ ಮುಖ್ಯ ಉದ್ದೇಶ ಏನು?',
    'hq.hq_qaoffice_1.a':       'ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರಿಗೆ ಶೆಲ್ಫ್ ಸ್ಥಳ ಮತ್ತು ಉತ್ಪನ್ನ ತಿರುಗುವಿಕೆ ನಿರ್ವಹಿಸಲು ಸಹಾಯ.',
    'hq.hq_qaoffice_1.b':       'ನಿರೀಕ್ಷಿತ ಗುಣಮಟ್ಟ ಮತ್ತು ಸುರಕ್ಷಿತತೆ ಅವಧಿ ಅಂದಾಜು ನೀಡಲು.',
    'hq.hq_qaoffice_1.c':       'ಗ್ರಾಹಕರು ತುಂಬಾ ಹಳೆಯ ಆಹಾರ ತಿನ್ನುವುದು ತಡೆಯಲು.',
    'hq.hq_qaoffice_1.d':       'ಆಹಾರ ಸುರಕ್ಷತಾ ಅಧಿಕಾರಿಗಳ ಕಾನೂನು ಅವಶ್ಯಕತೆ ಪೂರೈಸಲು.',
    'hq.hq_qaoffice_2.title':   'ಡಿಜಿಟಲ್ ಭದ್ರತೆ: ಸಾಫ್ಟ್‌ವೇರ್ ನವೀಕರಣ',
    'hq.hq_qaoffice_2.body':    'ಡಿಜಿಟಲ್ ಭದ್ರತಾ ಗುಣಮಟ್ಟಕ್ಕೆ ಸಾಫ್ಟ್‌ವೇರ್ ನವೀಕರಣ ಏಕೆ ಮುಖ್ಯ?',
    'hq.hq_qaoffice_2.a':       'ನವೀಕರಣ ಸಾಮಾನ್ಯವಾಗಿ ದೋಷಗಳನ್ನು ಸರಿಪಡಿಸಿ ವ್ಯವಸ್ಥಾ ರಕ್ಷಣೆ ಸುಧಾರಿಸುತ್ತದೆ.',
    'hq.hq_qaoffice_2.b':       'ನವೀಕರಣ ಮುಖ್ಯವಾಗಿ ಹೊಸ ವೈಶಿಷ್ಟ್ಯ ಸೇರಿಸಿ ಕಾರ್ಯಕ್ಷಮತೆ ಸುಧಾರಿಸುತ್ತದೆ.',
    'hq.hq_qaoffice_2.c':       'ಸಾಫ್ಟ್‌ವೇರ್ ಪರವಾನಗಿ ಅನುಸರಣೆ ಕಾಯ್ದುಕೊಳ್ಳಲು ನವೀಕರಣ ಅಗತ್ಯ.',
    'hq.hq_qaoffice_2.d':       'ನವೀಕರಣ ತಯಾರಕರಿಗೆ ಸಾಫ್ಟ್‌ವೇರ್ ಬಳಕೆ ಮಾದರಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಸಹಾಯ.',
    'hq.hq_dispatch_1.title':   'ಜೇನು ಗುಣಮಟ್ಟ: ನೈಸರ್ಗಿಕ ಚಿಹ್ನೆ',
    'hq.hq_dispatch_1.body':    'ಜೇನು ನೈಸರ್ಗಿಕ ಮತ್ತು ಕನಿಷ್ಠ ಸಂಸ್ಕರಣೆ ಆಗಿದೆ ಎಂಬ ಒಂದು ಸಾಮಾನ್ಯ ಚಿಹ್ನೆ ಯಾವುದು?',
    'hq.hq_dispatch_1.a':       'ಜೇನು ದೀರ್ಘ ಸಂಗ್ರಹದಲ್ಲಿ ನಿಧಾನವಾಗಿ ಹರಳಾಗಬಹುದು.',
    'hq.hq_dispatch_1.b':       'ಜೇನು ಯಾವಾಗಲೂ ಸಂಪೂರ್ಣ ಸ್ಪಷ್ಟ ಮತ್ತು ಪಾರದರ್ಶಕ.',
    'hq.hq_dispatch_1.c':       'ಬಾಟಲಿ ಮಾಡಿದ ನಂತರ ಜೇನು ಎಂದೂ ಬಣ್ಣ ಬದಲಾಯಿಸುವುದಿಲ್ಲ.',
    'hq.hq_dispatch_1.d':       'ಜೇನು ಮೇಲ್ಮೈಯಲ್ಲಿ ಸ್ವಲ್ಪ ನೊರೆ ಪದರ ಉಂಟಾಗುತ್ತದೆ.',
    'hq.hq_dispatch_2.title':   'ಗುಣಮಟ್ಟ ನಿಯಂತ್ರಣ: ಮಾದರಿ ವಿಧಾನ',
    'hq.hq_dispatch_2.body':    'ಕಾರ್ಖಾನೆ ಕೆಲವೊಮ್ಮೆ ಪ್ರತಿ ವಸ್ತು ಬದಲು ಯಾದೃಚ್ಛಿಕ ಉತ್ಪನ್ನ ಪರೀಕ್ಷಿಸುವುದೇಕೆ?',
    'hq.hq_dispatch_2.a':       'ಯಾದೃಚ್ಛಿಕ ಮಾದರಿ ಉತ್ಪಾದನಾ ಬ್ಯಾಚ್‌ನಲ್ಲಿ ಸಮಸ್ಯೆ ಪರಿಣಾಮಕಾರಿಯಾಗಿ ಗುರುತಿಸಬಹುದು.',
    'hq.hq_dispatch_2.b':       'ಹೆಚ್ಚಿನ ತಯಾರಿಕಾ ಸಂದರ್ಭದಲ್ಲಿ ಪ್ರತಿ ವಸ್ತು ಪರೀಕ್ಷಿಸುವುದು ತುಂಬಾ ದುಬಾರಿ.',
    'hq.hq_dispatch_2.c':       'ಅಂತರರಾಷ್ಟ್ರೀಯ ಗುಣಮಟ್ಟ ಮಾನದಂಡ ಯಾದೃಚ್ಛಿಕ ಪರೀಕ್ಷೆ ಅಗತ್ಯಪಡಿಸುತ್ತದೆ.',
    'hq.hq_dispatch_2.d':       'ಮಾದರಿ ಗುಣಮಟ್ಟ ಲೆಕ್ಕಪರಿಶೋಧನೆ ಮುಗಿಸಲು ಬೇಕಾದ ಸಮಯ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.',
    'btn.verify_release': 'ಪರಿಶೀಲಿಸಿ & ಬಿಡುಗಡೆ',
    'msg.kicked': 'ನಿರ್ವಾಹಕ ಸೂಚನೆ: {reason}\nದಯವಿಟ್ಟು ಪುಟ ರಿಫ್ರೆಶ್ ಮಾಡಿ ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಿ.',
    'login.loading_groups': 'ತಂಡಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…',
    'login.retry_groups':   '↺ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
"""

text = open('translations.js').read()
close_pos = text.find('\n  },\n\n  /* ─── TAMIL')
new_text = text[:close_pos] + '\n' + EXTRA + text[close_pos:]
open('translations.js', 'w').write(new_text)
print(f"Done. {len(text)} -> {len(new_text)} chars")
