#!/usr/bin/env python3
"""Replace old 5-question HQ blocks with new 10-question HQ blocks in all language sections.
Danish is KEPT. Kannada is handled separately."""

HQ = {
  'en': [
    ('hq_receiving_1','Food Quality: Everyday Test',
     'How can you most reliably check if an egg is spoiled before cooking it?',
     'Place it in cold water — a floating egg is likely spoiled.',
     'Crack it open and check the colour of the yolk.',
     'Shake it gently — a spoiled egg will feel heavier.',
     'Smell the outside of the shell before cracking it.'),
    ('hq_receiving_2','Air Quality: Colour Codes',
     "Which colour on most air quality indexes usually represents 'good' air quality?",
     'Red — indicating high pollution levels.',
     'Yellow — meaning moderate air quality is present.',
     'Green — indicating very low pollution measurements.',
     'Purple — signifying the cleanest possible air quality.'),
    ('hq_production_1','Water Quality: Safety Signs',
     'What is one common sign that tap water may not be safe to drink?',
     'The water appears slightly colder than usual.',
     'The water produces unusual odour after being poured.',
     'The water takes longer to come out of the tap.',
     'The water feels slightly warmer than normal.'),
    ('hq_production_2','Manufacturing: Barcode Benefits',
     'What does a barcode mainly help companies improve?',
     'Product appearance and packaging design quality.',
     'Inventory tracking accuracy across supply chain systems.',
     'Customer satisfaction ratings and brand loyalty.',
     'Employee productivity and workplace safety scores.'),
    ('hq_qclab_1','Environmental Quality: Urban Trees',
     'Why are trees important for improving urban environmental quality?',
     'Trees mainly provide shade to reduce building temperatures.',
     'Trees reduce noise and help filter airborne pollutants.',
     'Trees primarily increase property values in city areas.',
     'Trees are important mainly for wildlife habitat creation.'),
    ('hq_qclab_2','Product Quality: Pre-Shipping Inspection',
     'Why do many electronics include quality control inspections before shipping?',
     'To comply with customs regulations in destination countries.',
     'To identify defects before products reach final customers.',
     'To increase the overall weight of shipments for insurance.',
     'To reduce the need for product warranties after purchase.'),
    ('hq_qaoffice_1','Quality Systems: Expiration Dates',
     'What is the main purpose of expiration dates on packaged food products?',
     'To help retailers manage shelf space and product rotation.',
     'To estimate the period of expected quality and safety.',
     'To prevent consumers from eating food that is too old.',
     'To meet legal requirements set by food safety authorities.'),
    ('hq_qaoffice_2','Digital Security: Software Updates',
     'Why are software updates important for digital security quality?',
     'Updates often fix vulnerabilities and improve system protection.',
     'Updates mainly add new features and improve performance.',
     'Updates are required to maintain software licensing compliance.',
     'Updates help manufacturers track software usage patterns.'),
    ('hq_dispatch_1','Honey Quality: Natural Signs',
     'What is one common sign that honey is natural and minimally processed?',
     'The honey may slowly crystallise during long storage periods.',
     'The honey always remains completely clear and transparent.',
     'The honey never changes colour after being bottled.',
     'The honey produces a slight foam layer at the surface.'),
    ('hq_dispatch_2','Quality Control: Sampling Methods',
     'Why do factories sometimes test random products instead of every item?',
     'Random sampling can efficiently identify problems within production batches.',
     'Testing every item is too expensive in most manufacturing contexts.',
     'Random testing is required by international quality standards.',
     'Sampling reduces the time needed to complete quality audits.'),
  ],
  'de': [
    ('hq_receiving_1','Lebensmittelqualität: Alltagstest',
     'Wie kann man am zuverlässigsten prüfen, ob ein Ei verdorben ist, bevor man es kocht?',
     'In kaltes Wasser legen — ein schwimmendes Ei ist wahrscheinlich verdorben.',
     'Aufschlagen und die Farbe des Eigelbs prüfen.',
     'Sanft schütteln — ein verdorbenes Ei fühlt sich schwerer an.',
     'Die Außenseite der Schale vor dem Aufschlagen riechen.'),
    ('hq_receiving_2','Luftqualität: Farbcodes',
     'Welche Farbe steht auf den meisten Luftqualitätsindizes für „gute" Luftqualität?',
     'Rot — zeigt hohe Schadstoffwerte an.',
     'Gelb — bedeutet mäßige Luftqualität.',
     'Grün — zeigt sehr niedrige Schadstoffwerte an.',
     'Lila — steht für die sauberste mögliche Luftqualität.'),
    ('hq_production_1','Wasserqualität: Sicherheitszeichen',
     'Was ist ein häufiges Anzeichen dafür, dass Leitungswasser möglicherweise nicht sicher zum Trinken ist?',
     'Das Wasser erscheint etwas kälter als gewöhnlich.',
     'Das Wasser hat nach dem Einschenken einen ungewöhnlichen Geruch.',
     'Das Wasser läuft langsamer aus dem Hahn.',
     'Das Wasser fühlt sich etwas wärmer als normal an.'),
    ('hq_production_2','Fertigung: Barcode-Vorteile',
     'Wobei helfen Barcodes Unternehmen hauptsächlich?',
     'Produktaussehen und Verpackungsdesign.',
     'Genauigkeit der Bestandsverfolgung in Lieferketten.',
     'Kundenzufriedenheitsbewertungen und Markentreue.',
     'Mitarbeiterproduktivität und Arbeitsschutz.'),
    ('hq_qclab_1','Umweltqualität: Stadtbäume',
     'Warum sind Bäume wichtig für die Verbesserung der urbanen Umweltqualität?',
     'Bäume spenden hauptsächlich Schatten zur Kühlung von Gebäuden.',
     'Bäume reduzieren Lärm und filtern Luftschadstoffe.',
     'Bäume erhöhen hauptsächlich Immobilienwerte in Städten.',
     'Bäume sind vor allem für die Schaffung von Wildtierlebensräumen wichtig.'),
    ('hq_qclab_2','Produktqualität: Vorversandkontrolle',
     'Warum werden viele Elektronikprodukte vor dem Versand einer Qualitätskontrolle unterzogen?',
     'Um Zollvorschriften in Zielländern zu erfüllen.',
     'Um Mängel zu erkennen, bevor Produkte Endkunden erreichen.',
     'Um das Gesamtgewicht der Sendungen für Versicherungen zu erhöhen.',
     'Um den Bedarf an Produktgarantien nach dem Kauf zu verringern.'),
    ('hq_qaoffice_1','Qualitätssysteme: Ablaufdaten',
     'Was ist der Hauptzweck von Ablaufdaten auf verpackten Lebensmitteln?',
     'Einzelhändlern bei der Regalverwaltung und Produktrotation zu helfen.',
     'Den Zeitraum der erwarteten Qualität und Sicherheit abzuschätzen.',
     'Verbraucher daran zu hindern, zu altes Essen zu verzehren.',
     'Gesetzliche Anforderungen von Lebensmittelbehörden zu erfüllen.'),
    ('hq_qaoffice_2','Digitale Sicherheit: Software-Updates',
     'Warum sind Software-Updates für die Qualität der digitalen Sicherheit wichtig?',
     'Updates beheben häufig Sicherheitslücken und verbessern den Systemschutz.',
     'Updates fügen hauptsächlich neue Funktionen hinzu und verbessern die Leistung.',
     'Updates sind erforderlich, um die Softwarelizenz-Compliance zu erhalten.',
     'Updates helfen Herstellern, Software-Nutzungsmuster zu verfolgen.'),
    ('hq_dispatch_1','Honigqualität: Natürliche Zeichen',
     'Was ist ein häufiges Zeichen dafür, dass Honig natürlich und minimal verarbeitet ist?',
     'Honig kann sich bei langer Lagerung langsam kristallisieren.',
     'Honig bleibt immer vollständig klar und transparent.',
     'Honig verändert nach der Abfüllung nie seine Farbe.',
     'Honig bildet eine leichte Schaumschicht auf der Oberfläche.'),
    ('hq_dispatch_2','Qualitätskontrolle: Stichprobenmethoden',
     'Warum testen Fabriken manchmal zufällige Produkte anstatt jedes Exemplar?',
     'Stichproben können Probleme in Produktionschargen effizient identifizieren.',
     'Das Testen jedes Artikels ist in den meisten Fertigungskontexten zu teuer.',
     'Stichprobentests werden durch internationale Qualitätsstandards vorgeschrieben.',
     'Stichprobenentnahme reduziert den Zeitaufwand für Qualitätsprüfungen.'),
  ],
  'es': [
    ('hq_receiving_1','Calidad alimentaria: prueba cotidiana',
     '¿Cómo puedes comprobar de forma más fiable si un huevo está en mal estado antes de cocinarlo?',
     'Colócalo en agua fría: si flota, probablemente está en mal estado.',
     'Ábrelo y comprueba el color de la yema.',
     'Agítalo suavemente: un huevo en mal estado pesará más.',
     'Huele la cáscara por fuera antes de abrirlo.'),
    ('hq_receiving_2','Calidad del aire: códigos de color',
     '¿Qué color representa habitualmente la «buena» calidad del aire en la mayoría de los índices?',
     'Rojo: indica niveles altos de contaminación.',
     'Amarillo: significa calidad del aire moderada.',
     'Verde: indica niveles de contaminación muy bajos.',
     'Morado: indica la calidad del aire más limpia posible.'),
    ('hq_production_1','Calidad del agua: señales de alerta',
     '¿Cuál es una señal común de que el agua del grifo puede no ser segura para beber?',
     'El agua parece algo más fría de lo habitual.',
     'El agua produce un olor inusual al verterla.',
     'El agua tarda más en salir del grifo.',
     'El agua se siente algo más caliente de lo normal.'),
    ('hq_production_2','Fabricación: beneficios del código de barras',
     '¿En qué ayuda principalmente un código de barras a las empresas?',
     'Apariencia del producto y calidad del diseño de embalaje.',
     'Precisión del seguimiento de inventario en sistemas de cadena de suministro.',
     'Valoraciones de satisfacción del cliente y fidelidad de marca.',
     'Productividad de los empleados y puntuaciones de seguridad laboral.'),
    ('hq_qclab_1','Calidad ambiental: árboles urbanos',
     '¿Por qué son importantes los árboles para mejorar la calidad ambiental urbana?',
     'Los árboles proporcionan principalmente sombra para reducir la temperatura de los edificios.',
     'Los árboles reducen el ruido y ayudan a filtrar los contaminantes del aire.',
     'Los árboles aumentan principalmente el valor de las propiedades en las ciudades.',
     'Los árboles son importantes principalmente para crear hábitats para la vida silvestre.'),
    ('hq_qclab_2','Calidad del producto: inspección previa al envío',
     '¿Por qué muchos productos electrónicos incluyen inspecciones de control de calidad antes del envío?',
     'Para cumplir con las regulaciones aduaneras en los países de destino.',
     'Para identificar defectos antes de que los productos lleguen a los clientes finales.',
     'Para aumentar el peso total de los envíos para seguros.',
     'Para reducir la necesidad de garantías de productos tras la compra.'),
    ('hq_qaoffice_1','Sistemas de calidad: fechas de caducidad',
     '¿Cuál es el propósito principal de las fechas de caducidad en los productos alimenticios envasados?',
     'Ayudar a los minoristas a gestionar el espacio en estantes y la rotación de productos.',
     'Estimar el período de calidad y seguridad esperados.',
     'Evitar que los consumidores coman alimentos demasiado viejos.',
     'Cumplir con los requisitos legales establecidos por las autoridades de seguridad alimentaria.'),
    ('hq_qaoffice_2','Seguridad digital: actualizaciones de software',
     '¿Por qué son importantes las actualizaciones de software para la calidad de la seguridad digital?',
     'Las actualizaciones a menudo corrigen vulnerabilidades y mejoran la protección del sistema.',
     'Las actualizaciones principalmente añaden nuevas funciones y mejoran el rendimiento.',
     'Las actualizaciones son necesarias para mantener el cumplimiento de las licencias de software.',
     'Las actualizaciones ayudan a los fabricantes a rastrear los patrones de uso del software.'),
    ('hq_dispatch_1','Calidad de la miel: señales naturales',
     '¿Cuál es una señal común de que la miel es natural y mínimamente procesada?',
     'La miel puede cristalizarse lentamente durante períodos de almacenamiento prolongados.',
     'La miel siempre permanece completamente clara y transparente.',
     'La miel nunca cambia de color después de ser embotellada.',
     'La miel produce una ligera capa de espuma en la superficie.'),
    ('hq_dispatch_2','Control de calidad: métodos de muestreo',
     '¿Por qué las fábricas a veces prueban productos al azar en lugar de cada artículo?',
     'El muestreo aleatorio puede identificar eficientemente problemas en los lotes de producción.',
     'Probar cada artículo es demasiado costoso en la mayoría de los contextos de fabricación.',
     'Las pruebas aleatorias son requeridas por los estándares internacionales de calidad.',
     'El muestreo reduce el tiempo necesario para completar las auditorías de calidad.'),
  ],
  'da': [
    ('hq_receiving_1','Fødevarekvalitet: Hverdagstest',
     'Hvordan kan du mest pålideligt kontrollere, om et æg er forkælet, inden du koger det?',
     'Læg det i koldt vand — et flydende æg er sandsynligvis forkælet.',
     'Knæk det og kontroller blommens farve.',
     'Ryst det forsigtigt — et forkælet æg vil føles tungere.',
     'Lugt til ydersiden af skallen, inden du knækker det.'),
    ('hq_receiving_2','Luftkvalitet: Farvekoder',
     "Hvilken farve på de fleste luftkvalitetsindeks repræsenterer normalt 'god' luftkvalitet?",
     'Rød — angiver høje forureningsniveauer.',
     'Gul — betyder moderat luftkvalitet.',
     'Grøn — angiver meget lave forureningsniveauer.',
     'Lilla — angiver den renest mulige luftkvalitet.'),
    ('hq_production_1','Vandkvalitet: Sikkerhedstegn',
     'Hvad er et almindeligt tegn på, at vand fra hanen måske ikke er sikkert at drikke?',
     'Vandet ser en smule koldere ud end normalt.',
     'Vandet afgiver en usædvanlig lugt, efter det er hældt op.',
     'Vandet tager længere tid at komme ud af hanen.',
     'Vandet føles en smule varmere end normalt.'),
    ('hq_production_2','Fremstilling: Stregkodefordele',
     'Hvad hjælper en stregkode primært virksomheder med at forbedre?',
     'Produktets udseende og emballagedesignkvalitet.',
     'Nøjagtighed af lagerstyring på tværs af forsyningskædesystemer.',
     'Kundetilfredshedsvurderinger og brandloyalitet.',
     'Medarbejderproduktivitet og arbejdspladsikkerhedsscorer.'),
    ('hq_qclab_1','Miljøkvalitet: Bytræer',
     'Hvorfor er træer vigtige for at forbedre den urbane miljøkvalitet?',
     'Træer giver primært skygge for at reducere bygningers temperatur.',
     'Træer reducerer støj og hjælper med at filtrere luftbårne forureningsstoffer.',
     'Træer øger primært ejendomsværdierne i byområder.',
     'Træer er vigtige primært for skabelsen af dyrelivs-habitater.'),
    ('hq_qclab_2','Produktkvalitet: Inspektion før forsendelse',
     'Hvorfor gennemgår mange elektroniske produkter kvalitetskontrolinspektioner inden forsendelse?',
     'For at overholde toldregler i destinationslandene.',
     'For at identificere fejl, inden produkterne når de endelige kunder.',
     'For at øge forsendelsernes samlede vægt til forsikringsformål.',
     'For at reducere behovet for produktgarantier efter købet.'),
    ('hq_qaoffice_1','Kvalitetssystemer: Udløbsdatoer',
     'Hvad er det primære formål med udløbsdatoer på emballerede fødevareprodukter?',
     'At hjælpe detailhandlere med at styre hyldeплads og produktrotation.',
     'At estimere perioden med forventet kvalitet og sikkerhed.',
     'At forhindre forbrugere i at spise for gammelt mad.',
     'At opfylde lovkrav fastsat af fødevaresikkerhedsmyndigheder.'),
    ('hq_qaoffice_2','Digital sikkerhed: Softwareopdateringer',
     'Hvorfor er softwareopdateringer vigtige for den digitale sikkerhedskvalitet?',
     'Opdateringer retter ofte sårbarheder og forbedrer systembeskyttelsen.',
     'Opdateringer tilføjer primært nye funktioner og forbedrer ydeevnen.',
     'Opdateringer er nødvendige for at opretholde softwarelicensoverholdelse.',
     'Opdateringer hjælper producenter med at spore softwarebrugsmønstre.'),
    ('hq_dispatch_1','Honningkvalitet: Naturlige tegn',
     'Hvad er et almindeligt tegn på, at honning er naturlig og minimalt forarbejdet?',
     'Honningen kan langsomt krystallisere under lange opbevaringsperioder.',
     'Honningen forbliver altid helt klar og gennemsigtig.',
     'Honningen skifter aldrig farve, efter den er fyldt på flaske.',
     'Honningen danner et let skumlag på overfladen.'),
    ('hq_dispatch_2','Kvalitetskontrol: Stikprøvemetoder',
     'Hvorfor tester fabrikker nogle gange tilfældige produkter i stedet for hvert enkelt produkt?',
     'Tilfældig stikprøvetagning kan effektivt identificere problemer i produktionsbatches.',
     'Det er for dyrt at teste hvert enkelt produkt i de fleste produktionskontekster.',
     'Tilfældig testning er krævet af internationale kvalitetsstandarder.',
     'Stikprøvetagning reducerer den tid, der er nødvendig for at fuldføre kvalitetsrevisioner.'),
  ],
  'pt-BR': [
    ('hq_receiving_1','Qualidade alimentar: teste do dia a dia',
     'Como verificar de forma mais confiável se um ovo está estragado antes de cozinhá-lo?',
     'Coloque em água fria — se boiar, provavelmente está estragado.',
     'Quebre e verifique a cor da gema.',
     'Agite suavemente — um ovo estragado parecerá mais pesado.',
     'Cheire a casca por fora antes de quebrar.'),
    ('hq_receiving_2','Qualidade do ar: códigos de cores',
     "Qual cor representa geralmente a qualidade do ar 'boa' na maioria dos índices de qualidade do ar?",
     'Vermelho — indicando altos níveis de poluição.',
     'Amarelo — significando qualidade do ar moderada.',
     'Verde — indicando medições de poluição muito baixas.',
     'Roxo — indicando a qualidade do ar mais limpa possível.'),
    ('hq_production_1','Qualidade da água: sinais de alerta',
     'Qual é um sinal comum de que a água da torneira pode não ser segura para beber?',
     'A água parece um pouco mais fria do que o habitual.',
     'A água produz odor incomum após ser vertida.',
     'A água demora mais para sair da torneira.',
     'A água parece um pouco mais quente que o normal.'),
    ('hq_production_2','Manufatura: benefícios do código de barras',
     'O que o código de barras ajuda principalmente as empresas a melhorar?',
     'Aparência do produto e qualidade do design de embalagem.',
     'Precisão do rastreamento de estoque em sistemas de cadeia de suprimentos.',
     'Índices de satisfação do cliente e fidelidade à marca.',
     'Produtividade dos funcionários e pontuações de segurança no trabalho.'),
    ('hq_qclab_1','Qualidade ambiental: árvores urbanas',
     'Por que as árvores são importantes para melhorar a qualidade ambiental urbana?',
     'As árvores fornecem principalmente sombra para reduzir as temperaturas dos edifícios.',
     'As árvores reduzem o ruído e ajudam a filtrar poluentes do ar.',
     'As árvores aumentam principalmente o valor das propriedades nas cidades.',
     'As árvores são importantes principalmente para criar habitats para a vida selvagem.'),
    ('hq_qclab_2','Qualidade do produto: inspeção antes do envio',
     'Por que muitos eletrônicos incluem inspeções de controle de qualidade antes do envio?',
     'Para cumprir regulamentações aduaneiras nos países de destino.',
     'Para identificar defeitos antes que os produtos cheguem aos clientes finais.',
     'Para aumentar o peso total das remessas para fins de seguro.',
     'Para reduzir a necessidade de garantias de produtos após a compra.'),
    ('hq_qaoffice_1','Sistemas de qualidade: datas de validade',
     'Qual é o principal objetivo das datas de validade em produtos alimentícios embalados?',
     'Ajudar os varejistas a gerenciar o espaço nas prateleiras e a rotação de produtos.',
     'Estimar o período de qualidade e segurança esperados.',
     'Evitar que os consumidores comam alimentos muito velhos.',
     'Atender a requisitos legais estabelecidos pelas autoridades de segurança alimentar.'),
    ('hq_qaoffice_2','Segurança digital: atualizações de software',
     'Por que as atualizações de software são importantes para a qualidade da segurança digital?',
     'As atualizações frequentemente corrigem vulnerabilidades e melhoram a proteção do sistema.',
     'As atualizações adicionam principalmente novos recursos e melhoram o desempenho.',
     'As atualizações são necessárias para manter a conformidade com licenças de software.',
     'As atualizações ajudam os fabricantes a rastrear padrões de uso do software.'),
    ('hq_dispatch_1','Qualidade do mel: sinais naturais',
     'Qual é um sinal comum de que o mel é natural e minimamente processado?',
     'O mel pode cristalizar lentamente durante longos períodos de armazenamento.',
     'O mel sempre permanece completamente claro e transparente.',
     'O mel nunca muda de cor depois de ser engarrafado.',
     'O mel produz uma leve camada de espuma na superfície.'),
    ('hq_dispatch_2','Controle de qualidade: métodos de amostragem',
     'Por que as fábricas às vezes testam produtos aleatórios em vez de cada item?',
     'A amostragem aleatória pode identificar eficientemente problemas nos lotes de produção.',
     'Testar cada item é muito caro na maioria dos contextos de fabricação.',
     'O teste aleatório é exigido por padrões internacionais de qualidade.',
     'A amostragem reduz o tempo necessário para concluir auditorias de qualidade.'),
  ],
  'fr': [
    ('hq_receiving_1',"Qualité alimentaire : test quotidien",
     "Comment vérifier le plus sûrement si un œuf est avarié avant de le cuisiner ?",
     "Plongez-le dans de l'eau froide — un œuf qui flotte est probablement avarié.",
     "Cassez-le et vérifiez la couleur du jaune.",
     "Secouez-le doucement — un œuf avarié semblera plus lourd.",
     "Sentez l'extérieur de la coquille avant de le casser."),
    ('hq_receiving_2',"Qualité de l'air : codes couleur",
     "Quelle couleur représente généralement une bonne qualité de l'air sur la plupart des indices ?",
     "Rouge — indiquant des niveaux élevés de pollution.",
     "Jaune — signifiant une qualité de l'air modérée.",
     "Vert — indiquant des mesures de pollution très faibles.",
     "Violet — indiquant la qualité de l'air la plus pure possible."),
    ('hq_production_1',"Qualité de l'eau : signes d'alerte",
     "Quel est un signe courant que l'eau du robinet n'est peut-être pas sûre à boire ?",
     "L'eau semble légèrement plus froide que d'habitude.",
     "L'eau produit une odeur inhabituelle après avoir été versée.",
     "L'eau met plus de temps à sortir du robinet.",
     "L'eau semble légèrement plus chaude que la normale."),
    ('hq_production_2',"Fabrication : avantages du code-barres",
     "Dans quoi un code-barres aide-t-il principalement les entreprises ?",
     "Apparence du produit et qualité du design d'emballage.",
     "Précision du suivi des stocks dans les systèmes de chaîne d'approvisionnement.",
     "Évaluations de la satisfaction client et fidélité à la marque.",
     "Productivité des employés et scores de sécurité au travail."),
    ('hq_qclab_1',"Qualité environnementale : arbres urbains",
     "Pourquoi les arbres sont-ils importants pour améliorer la qualité environnementale urbaine ?",
     "Les arbres fournissent principalement de l'ombre pour réduire les températures des bâtiments.",
     "Les arbres réduisent le bruit et aident à filtrer les polluants atmosphériques.",
     "Les arbres augmentent principalement la valeur des propriétés dans les villes.",
     "Les arbres sont importants principalement pour créer des habitats pour la faune sauvage."),
    ('hq_qclab_2',"Qualité produit : inspection avant expédition",
     "Pourquoi de nombreux appareils électroniques incluent-ils des contrôles qualité avant expédition ?",
     "Pour se conformer aux réglementations douanières dans les pays de destination.",
     "Pour identifier les défauts avant que les produits n'atteignent les clients finaux.",
     "Pour augmenter le poids total des expéditions à des fins d'assurance.",
     "Pour réduire le besoin de garanties produits après l'achat."),
    ('hq_qaoffice_1',"Systèmes qualité : dates d'expiration",
     "Quel est le principal objectif des dates d'expiration sur les produits alimentaires emballés ?",
     "Aider les détaillants à gérer l'espace en rayon et la rotation des produits.",
     "Estimer la période de qualité et de sécurité attendue.",
     "Empêcher les consommateurs de manger des aliments trop vieux.",
     "Répondre aux exigences légales fixées par les autorités de sécurité alimentaire."),
    ('hq_qaoffice_2',"Sécurité numérique : mises à jour logicielles",
     "Pourquoi les mises à jour logicielles sont-elles importantes pour la qualité de la sécurité numérique ?",
     "Les mises à jour corrigent souvent des vulnérabilités et améliorent la protection du système.",
     "Les mises à jour ajoutent principalement de nouvelles fonctionnalités et améliorent les performances.",
     "Les mises à jour sont nécessaires pour maintenir la conformité des licences logicielles.",
     "Les mises à jour aident les fabricants à suivre les modèles d'utilisation des logiciels."),
    ('hq_dispatch_1',"Qualité du miel : signes naturels",
     "Quel est un signe courant que le miel est naturel et peu transformé ?",
     "Le miel peut cristalliser lentement pendant de longues périodes de stockage.",
     "Le miel reste toujours complètement clair et transparent.",
     "Le miel ne change jamais de couleur après la mise en bouteille.",
     "Le miel produit une légère couche de mousse à la surface."),
    ('hq_dispatch_2',"Contrôle qualité : méthodes d'échantillonnage",
     "Pourquoi les usines testent-elles parfois des produits aléatoires plutôt que chaque article ?",
     "L'échantillonnage aléatoire peut identifier efficacement les problèmes dans les lots de production.",
     "Tester chaque article est trop coûteux dans la plupart des contextes de fabrication.",
     "Les tests aléatoires sont requis par les normes de qualité internationales.",
     "L'échantillonnage réduit le temps nécessaire pour effectuer les audits qualité."),
  ],
  'ko': [
    ('hq_receiving_1','식품 품질: 일상 테스트',
     '요리하기 전에 달걀이 상했는지 가장 확실하게 확인하는 방법은?',
     '찬물에 넣었을 때 떠오르면 상한 달걀일 가능성이 높습니다.',
     '깨뜨려서 노른자 색깔을 확인합니다.',
     '살짝 흔들어 봅니다 — 상한 달걀은 더 무겁게 느껴집니다.',
     '깨뜨리기 전에 껍데기 바깥쪽 냄새를 맡아봅니다.'),
    ('hq_receiving_2','대기 품질: 색상 코드',
     "대부분의 대기질 지수에서 '좋은' 대기질을 나타내는 색상은?",
     '빨간색 — 높은 오염 수준을 나타냅니다.',
     '노란색 — 보통 수준의 대기질을 의미합니다.',
     '초록색 — 매우 낮은 오염 수준을 나타냅니다.',
     '보라색 — 가장 깨끗한 대기질을 의미합니다.'),
    ('hq_production_1','수질: 안전 신호',
     '수돗물이 마시기에 안전하지 않을 수 있다는 일반적인 징후는?',
     '물이 평소보다 약간 더 차갑게 보입니다.',
     '물을 따른 후 이상한 냄새가 납니다.',
     '물이 수도꼭지에서 나오는 데 더 오래 걸립니다.',
     '물이 평소보다 약간 더 따뜻하게 느껴집니다.'),
    ('hq_production_2','제조: 바코드의 이점',
     '바코드는 주로 기업의 무엇을 개선하는 데 도움을 줍니까?',
     '제품 외관 및 포장 디자인 품질.',
     '공급망 시스템 전반의 재고 추적 정확도.',
     '고객 만족도 평가 및 브랜드 충성도.',
     '직원 생산성 및 직장 안전 점수.'),
    ('hq_qclab_1','환경 품질: 도시 나무',
     '나무가 도시 환경 품질 개선에 중요한 이유는?',
     '나무는 주로 건물 온도를 낮추기 위한 그늘을 제공합니다.',
     '나무는 소음을 줄이고 공기 중 오염물질 필터링을 도와줍니다.',
     '나무는 주로 도시 지역의 부동산 가치를 높입니다.',
     '나무는 주로 야생동물 서식지 조성에 중요합니다.'),
    ('hq_qclab_2','제품 품질: 출하 전 검사',
     '많은 전자제품이 출하 전 품질 관리 검사를 포함하는 이유는?',
     '목적지 국가의 세관 규정을 준수하기 위해.',
     '제품이 최종 고객에게 도달하기 전에 결함을 식별하기 위해.',
     '보험을 위해 선적물의 전체 무게를 늘리기 위해.',
     '구매 후 제품 보증 필요성을 줄이기 위해.'),
    ('hq_qaoffice_1','품질 시스템: 유통기한',
     '포장 식품의 유통기한의 주된 목적은 무엇입니까?',
     '소매업체가 매대 공간 및 제품 순환을 관리하는 데 도움을 주기 위해.',
     '예상되는 품질 및 안전 기간을 추정하기 위해.',
     '소비자가 너무 오래된 음식을 먹지 못하도록 하기 위해.',
     '식품 안전 당국이 정한 법적 요구 사항을 충족하기 위해.'),
    ('hq_qaoffice_2','디지털 보안: 소프트웨어 업데이트',
     '소프트웨어 업데이트가 디지털 보안 품질에 중요한 이유는?',
     '업데이트는 종종 취약점을 수정하고 시스템 보호를 개선합니다.',
     '업데이트는 주로 새로운 기능을 추가하고 성능을 향상시킵니다.',
     '업데이트는 소프트웨어 라이센스 준수 유지에 필요합니다.',
     '업데이트는 제조업체가 소프트웨어 사용 패턴을 추적하는 데 도움을 줍니다.'),
    ('hq_dispatch_1','꿀 품질: 자연 신호',
     '꿀이 천연이고 최소한으로 가공되었다는 일반적인 징후는?',
     '꿀은 장기간 보관 중에 천천히 결정화될 수 있습니다.',
     '꿀은 항상 완전히 맑고 투명하게 유지됩니다.',
     '꿀은 병에 담긴 후 색이 변하지 않습니다.',
     '꿀은 표면에 약간의 거품층이 생깁니다.'),
    ('hq_dispatch_2','품질 관리: 샘플링 방법',
     '공장이 때때로 모든 제품 대신 무작위 제품을 테스트하는 이유는?',
     '무작위 샘플링은 생산 배치 내 문제를 효율적으로 식별할 수 있습니다.',
     '모든 항목을 테스트하는 것은 대부분의 제조 환경에서 비용이 너무 많이 듭니다.',
     '무작위 테스트는 국제 품질 표준에 의해 요구됩니다.',
     '샘플링은 품질 감사를 완료하는 데 필요한 시간을 줄여줍니다.'),
  ],
  'zh-Hans': [
    ('hq_receiving_1','食品质量：日常测试',
     '如何在烹饪前最可靠地检查鸡蛋是否变质？',
     '将鸡蛋放入冷水中——浮起的鸡蛋可能已变质。',
     '打开鸡蛋检查蛋黄的颜色。',
     '轻轻摇晃——变质的鸡蛋感觉更重。',
     '在打开之前闻一闻蛋壳外侧。'),
    ('hq_receiving_2','空气质量：颜色代码',
     "在大多数空气质量指数中，哪种颜色通常代表'良好'空气质量？",
     '红色——表示污染水平高。',
     '黄色——表示空气质量一般。',
     '绿色——表示污染水平非常低。',
     '紫色——表示空气质量最为清洁。'),
    ('hq_production_1','水质：安全信号',
     '自来水可能不安全饮用的一个常见迹象是什么？',
     '水看起来比平时略冷。',
     '倒水后产生异味。',
     '水从水龙头流出需要更长时间。',
     '水感觉比正常情况略暖。'),
    ('hq_production_2','制造：条形码优势',
     '条形码主要帮助企业改善什么？',
     '产品外观和包装设计质量。',
     '供应链系统中库存追踪的准确性。',
     '客户满意度评分和品牌忠诚度。',
     '员工生产力和工作场所安全评分。'),
    ('hq_qclab_1','环境质量：城市树木',
     '为什么树木对改善城市环境质量很重要？',
     '树木主要提供遮荫以降低建筑温度。',
     '树木减少噪音并帮助过滤空气中的污染物。',
     '树木主要提高城市地区的房产价值。',
     '树木主要用于为野生动物创造栖息地。'),
    ('hq_qclab_2','产品质量：发货前检验',
     '为什么许多电子产品在发货前要进行质量控制检验？',
     '为了遵守目的地国家的海关法规。',
     '为了在产品到达最终客户之前发现缺陷。',
     '为了增加货物总重量以满足保险需求。',
     '为了减少购买后产品保修的需求。'),
    ('hq_qaoffice_1','质量体系：保质期',
     '包装食品上保质期的主要目的是什么？',
     '帮助零售商管理货架空间和产品周转。',
     '估计预期的质量和安全期限。',
     '防止消费者食用过期食品。',
     '满足食品安全机构规定的法律要求。'),
    ('hq_qaoffice_2','数字安全：软件更新',
     '为什么软件更新对数字安全质量很重要？',
     '更新通常修复漏洞并改善系统保护。',
     '更新主要添加新功能并提高性能。',
     '更新是维持软件许可合规所必需的。',
     '更新帮助制造商追踪软件使用模式。'),
    ('hq_dispatch_1','蜂蜜质量：天然迹象',
     '蜂蜜天然且加工程度最低的一个常见迹象是什么？',
     '蜂蜜在长期储存期间可能会缓慢结晶。',
     '蜂蜜始终保持完全清澈透明。',
     '蜂蜜装瓶后颜色从不改变。',
     '蜂蜜在表面产生轻微的泡沫层。'),
    ('hq_dispatch_2','质量控制：抽样方法',
     '为什么工厂有时测试随机产品而不是每件产品？',
     '随机抽样可以有效识别生产批次中的问题。',
     '在大多数制造环境中，测试每件产品成本过高。',
     '国际质量标准要求进行随机测试。',
     '抽样减少了完成质量审核所需的时间。'),
  ],
  'zh-Hant': [
    ('hq_receiving_1','食品品質：日常測試',
     '如何在烹飪前最可靠地檢查雞蛋是否變質？',
     '將雞蛋放入冷水中——漂浮的雞蛋可能已變質。',
     '打開雞蛋檢查蛋黃的顏色。',
     '輕輕搖晃——變質的雞蛋感覺更重。',
     '在打開之前聞一聞蛋殼外側。'),
    ('hq_receiving_2','空氣品質：顏色代碼',
     "在大多數空氣品質指數中，哪種顏色通常代表「良好」空氣品質？",
     '紅色——表示污染水平高。',
     '黃色——表示空氣品質一般。',
     '綠色——表示污染水平非常低。',
     '紫色——表示空氣品質最為清潔。'),
    ('hq_production_1','水質：安全信號',
     '自來水可能不安全飲用的一個常見跡象是什麼？',
     '水看起來比平時略冷。',
     '倒水後產生異味。',
     '水從水龍頭流出需要更長時間。',
     '水感覺比正常情況略暖。'),
    ('hq_production_2','製造：條碼優勢',
     '條碼主要幫助企業改善什麼？',
     '產品外觀和包裝設計品質。',
     '供應鏈系統中庫存追蹤的準確性。',
     '客戶滿意度評分和品牌忠誠度。',
     '員工生產力和工作場所安全評分。'),
    ('hq_qclab_1','環境品質：城市樹木',
     '為什麼樹木對改善城市環境品質很重要？',
     '樹木主要提供遮蔭以降低建築溫度。',
     '樹木減少噪音並幫助過濾空氣中的污染物。',
     '樹木主要提高城市地區的房產價值。',
     '樹木主要用於為野生動物創造棲息地。'),
    ('hq_qclab_2','產品品質：發貨前檢驗',
     '為什麼許多電子產品在發貨前要進行品質控制檢驗？',
     '為了遵守目的地國家的海關法規。',
     '為了在產品到達最終客戶之前發現缺陷。',
     '為了增加貨物總重量以滿足保險需求。',
     '為了減少購買後產品保固的需求。'),
    ('hq_qaoffice_1','品質系統：保存期限',
     '包裝食品上保存期限的主要目的是什麼？',
     '幫助零售商管理貨架空間和產品周轉。',
     '估計預期的品質和安全期限。',
     '防止消費者食用過期食品。',
     '滿足食品安全機構規定的法律要求。'),
    ('hq_qaoffice_2','數位安全：軟體更新',
     '為什麼軟體更新對數位安全品質很重要？',
     '更新通常修復漏洞並改善系統保護。',
     '更新主要新增功能並提升效能。',
     '更新是維持軟體授權合規所必需的。',
     '更新幫助製造商追蹤軟體使用模式。'),
    ('hq_dispatch_1','蜂蜜品質：天然跡象',
     '蜂蜜天然且加工程度最低的一個常見跡象是什麼？',
     '蜂蜜在長期儲存期間可能會緩慢結晶。',
     '蜂蜜始終保持完全清澈透明。',
     '蜂蜜裝瓶後顏色從不改變。',
     '蜂蜜在表面產生輕微的泡沫層。'),
    ('hq_dispatch_2','品質控制：抽樣方法',
     '為什麼工廠有時測試隨機產品而不是每件產品？',
     '隨機抽樣可以有效識別生產批次中的問題。',
     '在大多數製造環境中，測試每件產品成本過高。',
     '國際品質標準要求進行隨機測試。',
     '抽樣減少了完成品質稽核所需的時間。'),
  ],
  'ms': [
    ('hq_receiving_1','Kualiti Makanan: Ujian Harian',
     'Bagaimana anda boleh menyemak dengan paling tepat sama ada telur telah rosak sebelum memasaknya?',
     'Letakkan dalam air sejuk — telur yang terapung mungkin telah rosak.',
     'Pecahkan dan semak warna kuning telur.',
     'Goncang perlahan-lahan — telur yang rosak akan terasa lebih berat.',
     'Hidu bahagian luar cengkerang sebelum memecahkannya.'),
    ('hq_receiving_2',"Kualiti Udara: Kod Warna",
     "Warna apakah yang biasanya mewakili kualiti udara 'baik' pada kebanyakan indeks kualiti udara?",
     'Merah — menunjukkan tahap pencemaran yang tinggi.',
     'Kuning — bermaksud kualiti udara sederhana.',
     'Hijau — menunjukkan pengukuran pencemaran yang sangat rendah.',
     'Ungu — menandakan kualiti udara paling bersih yang mungkin.'),
    ('hq_production_1','Kualiti Air: Tanda-Tanda Keselamatan',
     'Apakah tanda biasa bahawa air paip mungkin tidak selamat untuk diminum?',
     'Air kelihatan sedikit lebih sejuk daripada biasa.',
     'Air menghasilkan bau yang luar biasa selepas dituangkan.',
     'Air mengambil masa lebih lama untuk keluar dari paip.',
     'Air terasa sedikit lebih panas daripada biasa.'),
    ('hq_production_2','Pembuatan: Faedah Kod Bar',
     'Apakah yang terutamanya dibantu oleh kod bar untuk syarikat-syarikat?',
     'Penampilan produk dan kualiti reka bentuk pembungkusan.',
     'Ketepatan penjejakan inventori merentas sistem rantaian bekalan.',
     'Penilaian kepuasan pelanggan dan kesetiaan jenama.',
     'Produktiviti pekerja dan skor keselamatan tempat kerja.'),
    ('hq_qclab_1','Kualiti Alam Sekitar: Pokok Bandar',
     'Mengapa pokok penting untuk meningkatkan kualiti alam sekitar bandar?',
     'Pokok terutamanya menyediakan teduhan untuk mengurangkan suhu bangunan.',
     'Pokok mengurangkan bunyi bising dan membantu menapis bahan pencemar udara.',
     'Pokok terutamanya meningkatkan nilai hartanah di kawasan bandar.',
     'Pokok penting terutamanya untuk penciptaan habitat hidupan liar.'),
    ('hq_qclab_2','Kualiti Produk: Pemeriksaan Pra-Penghantaran',
     'Mengapa banyak produk elektronik termasuk pemeriksaan kawalan kualiti sebelum penghantaran?',
     'Untuk mematuhi peraturan kastam di negara-negara destinasi.',
     'Untuk mengenal pasti kecacatan sebelum produk sampai kepada pelanggan akhir.',
     'Untuk meningkatkan berat keseluruhan penghantaran untuk tujuan insurans.',
     'Untuk mengurangkan keperluan waranti produk selepas pembelian.'),
    ('hq_qaoffice_1','Sistem Kualiti: Tarikh Luput',
     'Apakah tujuan utama tarikh luput pada produk makanan bungkus?',
     'Untuk membantu peruncit mengurus ruang rak dan pusingan produk.',
     'Untuk menganggarkan tempoh kualiti dan keselamatan yang dijangkakan.',
     'Untuk mencegah pengguna daripada memakan makanan yang terlalu lama.',
     'Untuk memenuhi keperluan undang-undang yang ditetapkan oleh pihak berkuasa keselamatan makanan.'),
    ('hq_qaoffice_2','Keselamatan Digital: Kemas Kini Perisian',
     'Mengapa kemas kini perisian penting untuk kualiti keselamatan digital?',
     'Kemas kini sering memperbaiki kelemahan dan meningkatkan perlindungan sistem.',
     'Kemas kini terutamanya menambah ciri baharu dan meningkatkan prestasi.',
     'Kemas kini diperlukan untuk mengekalkan pematuhan pelesenan perisian.',
     'Kemas kini membantu pengeluar menjejaki corak penggunaan perisian.'),
    ('hq_dispatch_1','Kualiti Madu: Tanda-Tanda Semula Jadi',
     'Apakah tanda biasa bahawa madu adalah semula jadi dan diproses secara minimum?',
     'Madu mungkin perlahan-lahan mengkristal semasa tempoh penyimpanan yang lama.',
     'Madu sentiasa kekal jernih dan telus sepenuhnya.',
     'Madu tidak pernah berubah warna selepas dibotolkan.',
     'Madu menghasilkan lapisan buih yang sedikit di permukaan.'),
    ('hq_dispatch_2','Kawalan Kualiti: Kaedah Pensampelan',
     'Mengapa kilang kadang-kadang menguji produk rawak dan bukannya setiap item?',
     'Pensampelan rawak boleh mengenal pasti masalah dalam kelompok pengeluaran dengan cekap.',
     'Menguji setiap item terlalu mahal dalam kebanyakan konteks pembuatan.',
     'Ujian rawak diperlukan oleh piawaian kualiti antarabangsa.',
     'Pensampelan mengurangkan masa yang diperlukan untuk melengkapkan audit kualiti.'),
  ],
  'ta': [
    ('hq_receiving_1','உணவு தரம்: அன்றாட சோதனை',
     'சமைப்பதற்கு முன் முட்டை கெட்டுவிட்டதா என்பதை மிகவும் நம்பகமான முறையில் எவ்வாறு சரிபார்க்கலாம்?',
     'குளிர்ந்த நீரில் வைக்கவும் — மிதக்கும் முட்டை கெட்டதாக இருக்கலாம்.',
     'உடைத்து மஞ்சள் கருவின் நிறத்தை சரிபார்க்கவும்.',
     'மெதுவாக அசைக்கவும் — கெட்ட முட்டை கனமாக உணரும்.',
     'உடைப்பதற்கு முன் ஓட்டின் வெளிப்புறத்தை நுகரவும்.'),
    ('hq_receiving_2','காற்று தரம்: வண்ண குறியீடுகள்',
     "பெரும்பாலான காற்றுத் தர குறியீடுகளில் 'நல்ல' காற்றுத் தரத்தை பொதுவாக எந்த வண்ணம் குறிக்கிறது?",
     'சிவப்பு — அதிக மாசு அளவுகளை குறிக்கிறது.',
     'மஞ்சள் — மிதமான காற்றுத் தரத்தை குறிக்கிறது.',
     'பச்சை — மிகவும் குறைந்த மாசு அளவீடுகளை குறிக்கிறது.',
     'ஊதா — மிகவும் சுத்தமான காற்றுத் தரத்தை குறிக்கிறது.'),
    ('hq_production_1','நீர் தரம்: பாதுகாப்பு அறிகுறிகள்',
     'குழாய் நீர் குடிக்க பாதுகாப்பானதாக இல்லாமல் இருக்கலாம் என்பதற்கான ஒரு பொதுவான அறிகுறி என்ன?',
     'நீர் வழக்கத்தை விட சற்று குளிர்ச்சியாக தெரிகிறது.',
     'நீரை ஊற்றிய பிறகு அசாதாரண நறுமணம் வருகிறது.',
     'நீர் குழாயிலிருந்து வர அதிக நேரம் ஆகிறது.',
     'நீர் சாதாரணத்தை விட சற்று வெப்பமாக உணர்கிறது.'),
    ('hq_production_2','உற்பத்தி: பார்கோட் நன்மைகள்',
     'பார்கோட் முக்கியமாக நிறுவனங்களுக்கு எதை மேம்படுத்த உதவுகிறது?',
     'தயாரிப்பு தோற்றம் மற்றும் பேக்கேஜிங் வடிவமைப்பு தரம்.',
     'விநியோக சங்கிலி அமைப்புகளில் சரக்கு கண்காணிப்பு துல்லியம்.',
     'வாடிக்கையாளர் திருப்தி மதிப்பீடுகள் மற்றும் பிராண்ட் விசுவாசம்.',
     'ஊழியர் உற்பத்தித்திறன் மற்றும் பணியிட பாதுகாப்பு மதிப்பெண்கள்.'),
    ('hq_qclab_1','சுற்றுச்சூழல் தரம்: நகர மரங்கள்',
     'நகர சுற்றுச்சூழல் தரத்தை மேம்படுத்துவதில் மரங்கள் ஏன் முக்கியம்?',
     'மரங்கள் முக்கியமாக கட்டிட வெப்பநிலையை குறைக்க நிழல் அளிக்கின்றன.',
     'மரங்கள் சத்தத்தை குறைத்து காற்று மாசுகளை வடிகட்ட உதவுகின்றன.',
     'மரங்கள் முக்கியமாக நகர பகுதிகளில் சொத்து மதிப்பை அதிகரிக்கின்றன.',
     'மரங்கள் முக்கியமாக வனவிலங்கு வாழிடம் உருவாக்குவதில் முக்கியம்.'),
    ('hq_qclab_2','தயாரிப்பு தரம்: அனுப்புவதற்கு முந்தைய பரிசோதனை',
     'பல மின்னணு சாதனங்கள் ஏன் அனுப்புவதற்கு முன் தரக் கட்டுப்பாட்டு பரிசோதனைகளை உள்ளடக்குகின்றன?',
     'சேருமிட நாடுகளில் சுங்க விதிமுறைகளை கடைப்பிடிக்க.',
     'தயாரிப்புகள் இறுதி வாடிக்கையாளர்களை அடைவதற்கு முன் குறைபாடுகளை கண்டறிய.',
     'காப்பீட்டிற்காக ஏற்றுமதியின் மொத்த எடையை அதிகரிக்க.',
     'வாங்கிய பிறகு தயாரிப்பு உத்தரவாத தேவையை குறைக்க.'),
    ('hq_qaoffice_1','தர அமைப்புகள்: காலாவதி தேதிகள்',
     'பேக்கேஜ் செய்யப்பட்ட உணவு தயாரிப்புகளில் காலாவதி தேதிகளின் முக்கிய நோக்கம் என்ன?',
     'சில்லறை வியாபாரிகளுக்கு அலமாரி இடம் மற்றும் தயாரிப்பு சுழற்சியை நிர்வகிக்க உதவ.',
     'எதிர்பார்க்கப்படும் தரம் மற்றும் பாதுகாப்பு காலத்தை மதிப்பிட.',
     'நுகர்வோர் மிகவும் பழைய உணவை சாப்பிடுவதை தடுக்க.',
     'உணவு பாதுகாப்பு அதிகாரிகளால் நிர்ணயிக்கப்பட்ட சட்ட தேவைகளை பூர்த்தி செய்ய.'),
    ('hq_qaoffice_2','டிஜிட்டல் பாதுகாப்பு: மென்பொருள் புதுப்பிப்புகள்',
     'டிஜிட்டல் பாதுகாப்பு தரத்திற்கு மென்பொருள் புதுப்பிப்புகள் ஏன் முக்கியம்?',
     'புதுப்பிப்புகள் பெரும்பாலும் பாதிப்புகளை சரிசெய்து கணினி பாதுகாப்பை மேம்படுத்துகின்றன.',
     'புதுப்பிப்புகள் முக்கியமாக புதிய அம்சங்களை சேர்த்து செயல்திறனை மேம்படுத்துகின்றன.',
     'மென்பொருள் உரிம இணக்கத்தை பராமரிக்க புதுப்பிப்புகள் தேவை.',
     'புதுப்பிப்புகள் உற்பத்தியாளர்களுக்கு மென்பொருள் பயன்பாட்டு முறைகளை கண்காணிக்க உதவுகின்றன.'),
    ('hq_dispatch_1','தேன் தரம்: இயற்கை அறிகுறிகள்',
     'தேன் இயற்கையானது மற்றும் குறைந்தபட்சமாக பதப்படுத்தப்பட்டது என்பதற்கான ஒரு பொதுவான அறிகுறி என்ன?',
     'தேன் நீண்ட சேமிப்பு காலங்களில் மெதுவாக படிகமாகலாம்.',
     'தேன் எப்போதும் முழுமையாக தெளிவான மற்றும் வெளிப்படையாக இருக்கும்.',
     'தேன் பாட்டிலில் அடைக்கப்பட்ட பிறகு ஒருபோதும் நிறம் மாறாது.',
     'தேன் மேற்பரப்பில் சிறிது நுரை அடுக்கை உருவாக்குகிறது.'),
    ('hq_dispatch_2','தரக் கட்டுப்பாடு: மாதிரி முறைகள்',
     'தொழிற்சாலைகள் சில நேரங்களில் ஒவ்வொரு பொருளையும் சோதிக்காமல் சீரற்ற தயாரிப்புகளை சோதிப்பது ஏன்?',
     'சீரற்ற மாதிரியெடுத்தல் உற்பத்தி தொகுதிகளில் சிக்கல்களை திறமையாக கண்டறியலாம்.',
     'பெரும்பாலான உற்பத்தி சூழல்களில் ஒவ்வொரு பொருளையும் சோதிப்பது மிகவும் விலை உயர்ந்தது.',
     'சீரற்ற சோதனை சர்வதேச தர தரநிலைகளால் தேவைப்படுகிறது.',
     'மாதிரியெடுத்தல் தர தணிக்கைகளை முடிக்க தேவையான நேரத்தை குறைக்கிறது.'),
  ],
  'hi': [
    ('hq_receiving_1','खाद्य गुणवत्ता: रोज़मर्रा का परीक्षण',
     'पकाने से पहले यह सबसे विश्वसनीय तरीके से कैसे जांचें कि अंडा खराब है या नहीं?',
     'ठंडे पानी में रखें — तैरता हुआ अंडा संभवतः खराब है।',
     'तोड़कर जर्दी का रंग जांचें।',
     'धीरे से हिलाएं — खराब अंडा भारी लगेगा।',
     'तोड़ने से पहले छिलके के बाहरी भाग को सूंघें।'),
    ('hq_receiving_2','वायु गुणवत्ता: रंग कोड',
     "अधिकांश वायु गुणवत्ता सूचकांकों पर 'अच्छी' वायु गुणवत्ता के लिए आमतौर पर कौन सा रंग होता है?",
     'लाल — उच्च प्रदूषण स्तर दर्शाता है।',
     'पीला — मध्यम वायु गुणवत्ता दर्शाता है।',
     'हरा — बहुत कम प्रदूषण माप दर्शाता है।',
     'बैंगनी — सबसे स्वच्छ संभव वायु गुणवत्ता दर्शाता है।'),
    ('hq_production_1','जल गुणवत्ता: सुरक्षा संकेत',
     'नल का पानी पीने के लिए सुरक्षित नहीं हो सकता, इसका एक सामान्य संकेत क्या है?',
     'पानी सामान्य से थोड़ा ठंडा दिखता है।',
     'पानी डालने के बाद असामान्य गंध आती है।',
     'पानी नल से निकलने में अधिक समय लेता है।',
     'पानी सामान्य से थोड़ा गर्म लगता है।'),
    ('hq_production_2','विनिर्माण: बारकोड के लाभ',
     'बारकोड मुख्य रूप से कंपनियों को क्या सुधारने में मदद करता है?',
     'उत्पाद की उपस्थिति और पैकेजिंग डिज़ाइन गुणवत्ता।',
     'आपूर्ति श्रृंखला प्रणालियों में इन्वेंट्री ट्रैकिंग सटीकता।',
     'ग्राहक संतुष्टि रेटिंग और ब्रांड वफादारी।',
     'कर्मचारी उत्पादकता और कार्यस्थल सुरक्षा स्कोर।'),
    ('hq_qclab_1','पर्यावरण गुणवत्ता: शहरी पेड़',
     'शहरी पर्यावरण गुणवत्ता में सुधार के लिए पेड़ क्यों महत्वपूर्ण हैं?',
     'पेड़ मुख्य रूप से इमारत के तापमान को कम करने के लिए छाया प्रदान करते हैं।',
     'पेड़ शोर कम करते हैं और वायु प्रदूषकों को फ़िल्टर करने में मदद करते हैं।',
     'पेड़ मुख्य रूप से शहरी क्षेत्रों में संपत्ति का मूल्य बढ़ाते हैं।',
     'पेड़ मुख्य रूप से वन्यजीव आवास निर्माण के लिए महत्वपूर्ण हैं।'),
    ('hq_qclab_2','उत्पाद गुणवत्ता: शिपिंग से पहले निरीक्षण',
     'कई इलेक्ट्रॉनिक उत्पाद शिपिंग से पहले गुणवत्ता नियंत्रण निरीक्षण क्यों शामिल करते हैं?',
     'गंतव्य देशों में सीमा शुल्क नियमों का पालन करने के लिए।',
     'उत्पादों के अंतिम ग्राहकों तक पहुंचने से पहले दोषों की पहचान करने के लिए।',
     'बीमा के लिए शिपमेंट के कुल वजन को बढ़ाने के लिए।',
     'खरीद के बाद उत्पाद वारंटी की आवश्यकता को कम करने के लिए।'),
    ('hq_qaoffice_1','गुणवत्ता प्रणालियाँ: समाप्ति तिथियाँ',
     'पैकेज्ड खाद्य उत्पादों पर समाप्ति तिथियों का मुख्य उद्देश्य क्या है?',
     'खुदरा विक्रेताओं को शेल्फ स्पेस और उत्पाद रोटेशन प्रबंधित करने में मदद करना।',
     'अपेक्षित गुणवत्ता और सुरक्षा की अवधि का अनुमान लगाना।',
     'उपभोक्ताओं को बहुत पुराना खाना खाने से रोकना।',
     'खाद्य सुरक्षा अधिकारियों द्वारा निर्धारित कानूनी आवश्यकताओं को पूरा करना।'),
    ('hq_qaoffice_2','डिजिटल सुरक्षा: सॉफ़्टवेयर अपडेट',
     'डिजिटल सुरक्षा गुणवत्ता के लिए सॉफ़्टवेयर अपडेट क्यों महत्वपूर्ण हैं?',
     'अपडेट अक्सर कमज़ोरियों को ठीक करते हैं और सिस्टम सुरक्षा में सुधार करते हैं।',
     'अपडेट मुख्य रूप से नई सुविधाएं जोड़ते हैं और प्रदर्शन में सुधार करते हैं।',
     'सॉफ़्टवेयर लाइसेंसिंग अनुपालन बनाए रखने के लिए अपडेट आवश्यक हैं।',
     'अपडेट निर्माताओं को सॉफ़्टवेयर उपयोग पैटर्न ट्रैक करने में मदद करते हैं।'),
    ('hq_dispatch_1','शहद की गुणवत्ता: प्राकृतिक संकेत',
     'शहद प्राकृतिक और न्यूनतम प्रसंस्कृत है, इसका एक सामान्य संकेत क्या है?',
     'शहद लंबे भंडारण अवधि के दौरान धीरे-धीरे क्रिस्टलीकृत हो सकता है।',
     'शहद हमेशा पूरी तरह से स्पष्ट और पारदर्शी रहता है।',
     'शहद बोतलबंद होने के बाद कभी रंग नहीं बदलता।',
     'शहद सतह पर एक हल्की झाग की परत बनाता है।'),
    ('hq_dispatch_2','गुणवत्ता नियंत्रण: नमूनाकरण विधियाँ',
     'कारखाने कभी-कभी हर वस्तु के बजाय यादृच्छिक उत्पादों का परीक्षण क्यों करते हैं?',
     'यादृच्छिक नमूनाकरण उत्पादन बैचों में समस्याओं की कुशलता से पहचान कर सकता है।',
     'अधिकांश विनिर्माण संदर्भों में हर वस्तु का परीक्षण बहुत महंगा है।',
     'यादृच्छिक परीक्षण अंतर्राष्ट्रीय गुणवत्ता मानकों द्वारा आवश्यक है।',
     'नमूनाकरण गुणवत्ता ऑडिट पूरा करने के लिए आवश्यक समय को कम करता है।'),
  ],
  'sr-Latn': [
    ('hq_receiving_1','Kvalitet hrane: Svakodnevni test',
     'Kako najpouzdanije provjeriti je li jaje pokvareno prije kuhanja?',
     'Stavite u hladnu vodu — jaje koje pluta vjerovatno je pokvareno.',
     'Razbijte ga i provjerite boju žumanca.',
     'Nježno protresite — pokvareno jaje će se osjećati teže.',
     'Pomirišite vanjsku stranu ljuske prije lomljenja.'),
    ('hq_receiving_2','Kvalitet vazduha: Kodni kolori',
     "Koja boja na većini indeksa kvaliteta vazduha obično predstavlja 'dobar' kvalitet vazduha?",
     'Crvena — ukazuje na visoke nivoe zagađenja.',
     'Žuta — znači umjeren kvalitet vazduha.',
     'Zelena — ukazuje na vrlo niske mjere zagađenja.',
     'Ljubičasta — označava najčistiji mogući kvalitet vazduha.'),
    ('hq_production_1','Kvalitet vode: Signosni znaci',
     'Koji je čest znak da voda iz slavine možda nije bezbjedna za piće?',
     'Voda izgleda nešto hladnija nego inače.',
     'Voda ima neobičan miris nakon točenja.',
     'Voda duže teče iz slavine.',
     'Voda se osjeća nešto toplija od uobičajenog.'),
    ('hq_production_2','Proizvodnja: Prednosti barkoda',
     'U čemu barkod uglavnom pomaže kompanijama da se poboljšaju?',
     'Izgled proizvoda i kvalitet dizajna ambalaže.',
     'Tačnost praćenja inventara u sistemima lanca snabdijevanja.',
     'Ocjene zadovoljstva kupaca i lojalnost brendu.',
     'Produktivnost zaposlenika i ocjene sigurnosti na radu.'),
    ('hq_qclab_1','Kvalitet životne sredine: Gradsko drveće',
     'Zašto je drveće važno za poboljšanje kvaliteta urbane životne sredine?',
     'Drveće uglavnom pruža hlad za smanjenje temperature zgrada.',
     'Drveće smanjuje buku i pomaže u filtriranju zagađivača u zraku.',
     'Drveće uglavnom povećava vrijednost nekretnina u gradskim područjima.',
     'Drveće je važno uglavnom za stvaranje staništa divljih životinja.'),
    ('hq_qclab_2','Kvalitet proizvoda: Inspekcija prije slanja',
     'Zašto mnogi elektronski uređaji uključuju kontrolu kvaliteta prije slanja?',
     'Da bi se poštovale carinske propise u odredišnim zemljama.',
     'Da bi se otkrile greške prije nego što proizvodi dođu do krajnjih kupaca.',
     'Da bi se povećala ukupna težina pošiljki za osiguranje.',
     'Da bi se smanjila potreba za garancijama na proizvode nakon kupovine.'),
    ('hq_qaoffice_1','Sistemi kvaliteta: Datumi isteka',
     'Koja je glavna svrha datuma isteka na upakovanim prehrambenim proizvodima?',
     'Da pomognu maloprodavcima da upravljaju prostorom na policama i rotacijom proizvoda.',
     'Da procijene period očekivanog kvaliteta i bezbjednosti.',
     'Da spriječe potrošače da jedu prehrambene proizvode koji su previše stari.',
     'Da ispune zakonske zahtjeve koje su postavila tijela za bezbjednost hrane.'),
    ('hq_qaoffice_2','Digitalna bezbjednost: Ažuriranja softvera',
     'Zašto su ažuriranja softvera važna za kvalitet digitalne bezbjednosti?',
     'Ažuriranja često otklanjaju ranjivosti i poboljšavaju zaštitu sistema.',
     'Ažuriranja uglavnom dodaju nove funkcije i poboljšavaju performanse.',
     'Ažuriranja su neophodna za održavanje usklađenosti softverskog licenciranja.',
     'Ažuriranja pomažu proizvođačima da prate obrasce korištenja softvera.'),
    ('hq_dispatch_1','Kvalitet meda: Prirodni znaci',
     'Koji je čest znak da je med prirodan i minimalno obrađen?',
     'Med se može polako kristalizirati tokom dugih perioda skladištenja.',
     'Med uvijek ostaje potpuno bistar i proziran.',
     'Med nikada ne mijenja boju nakon punjenja u boce.',
     'Med stvara lagani sloj pjene na površini.'),
    ('hq_dispatch_2','Kontrola kvaliteta: Metode uzorkovanja',
     'Zašto fabrike ponekad testiraju nasumične proizvode umjesto svake stavke?',
     'Nasumično uzorkovanje može efikasno identificirati probleme unutar serija proizvodnje.',
     'Testiranje svake stavke je preskupo u većini konteksta proizvodnje.',
     'Nasumično testiranje zahtijevaju međunarodni standardi kvaliteta.',
     'Uzorkovanje smanjuje vrijeme potrebno za završetak revizija kvaliteta.'),
  ],
  'sr-Cyrl': [
    ('hq_receiving_1','Квалитет хране: Свакодневни тест',
     'Kako najpouzdanije provjeriti je li jaje pokvareno prije kuhanja?',
     'Ставите у хладну воду — јаје које плута вероватно је покварено.',
     'Разбијте га и проверите боју жуманца.',
     'Нежно протресите — покварено јаје ће се осећати теже.',
     'Помиришите спољашњу страну љуске пре ломљења.'),
    ('hq_receiving_2','Квалитет ваздуха: Кодне боје',
     "Која боја на већини индекса квалитета ваздуха обично представља 'добар' квалитет ваздуха?",
     'Црвена — указује на висок ниво загађења.',
     'Жута — значи умерен квалитет ваздуха.',
     'Зелена — указује на веома ниске мере загађења.',
     'Љубичаста — означава најчистији могући квалитет ваздуха.'),
    ('hq_production_1','Квалитет воде: Безбедносни знаци',
     'Који је чест знак да вода из чесме можда није безбедна за пиће?',
     'Вода изгледа нешто хладнија него иначе.',
     'Вода има необичан мирис након точења.',
     'Вода дуже тече из чесме.',
     'Вода се осећа нешто топлија од уобичајеног.'),
    ('hq_production_2','Производња: Предности бар-кода',
     'У чему бар-код углавном помаже компанијама да се побољшају?',
     'Изглед производа и квалитет дизајна амбалаже.',
     'Тачност праћења залиха у системима ланца снабдевања.',
     'Оцене задовољства купаца и лојалност бренду.',
     'Продуктивност запослених и оцене безбедности на раду.'),
    ('hq_qclab_1','Квалитет животне средине: Градско дрвеће',
     'Зашто је дрвеће важно за побољшање квалитета урбане животне средине?',
     'Дрвеће углавном пружа хлад за смањење температуре зграда.',
     'Дрвеће смањује буку и помаже у филтрирању загађивача у ваздуху.',
     'Дрвеће углавном повећава вредност некретнина у градским подручјима.',
     'Дрвеће је важно углавном за стварање станишта дивљих животиња.'),
    ('hq_qclab_2','Квалитет производа: Инспекција пре слања',
     'Зашто многи електронски уређаји укључују контролу квалитета пре слања?',
     'Да би се поштовали царински прописи у одредишним земљама.',
     'Да би се открили недостаци пре него што производи дођу до крајњих купаца.',
     'Да би се повећала укупна тежина пошиљки за осигурање.',
     'Да би се смањила потреба за гаранцијама на производе после куповине.'),
    ('hq_qaoffice_1','Системи квалитета: Датуми истека',
     'Која је главна сврха датума истека на упакованим прехрамбеним производима?',
     'Да помогну малопродавцима да управљају простором на полицама и ротацијом производа.',
     'Да процене период очекиваног квалитета и безбедности.',
     'Да спрече потрошаче даједу прехрамбене производе који су престари.',
     'Да испуне законске захтеве које су поставила тела за безбедност хране.'),
    ('hq_qaoffice_2','Дигитална безбедност: Ажурирања софтвера',
     'Зашто су ажурирања софтвера важна за квалитет дигиталне безбедности?',
     'Ажурирања често отклањају рањивости и побољшавају заштиту система.',
     'Ажурирања углавном додају нове функције и побољшавају перформансе.',
     'Ажурирања су неопходна за одржавање усклађености лиценцирања софтвера.',
     'Ажурирања помажу произвођачима да прате обрасце коришћења софтвера.'),
    ('hq_dispatch_1','Квалитет меда: Природни знаци',
     'Који је чест знак да је мед природан и минимално обрађен?',
     'Мед се може полако кристализовати током дугих периода складиштења.',
     'Мед увек остаје потпуно бистар и провидан.',
     'Мед никада не мења боју после пуњења у боце.',
     'Мед ствара лагани слој пене на површини.'),
    ('hq_dispatch_2','Контрола квалитета: Методе узорковања',
     'Зашто фабрике понекад тестирају насумичне производе уместо сваке ставке?',
     'Насумично узорковање може ефикасно идентификовати проблеме унутар серија производње.',
     'Тестирање сваке ставке је прескупо у већини контекста производње.',
     'Насумично тестирање захтевају међународни стандарди квалитета.',
     'Узорковање смањује време потребно за завршетак ревизија квалитета.'),
  ],
  'he': [
    ('hq_receiving_1','איכות מזון: מבחן יומיומי',
     'כיצד ניתן לבדוק בצורה האמינה ביותר אם ביצה קלוקלת לפני הבישול?',
     'הניחו אותה במים קרים — ביצה צפה כנראה קלוקלת.',
     'פתחו אותה ובדקו את צבע החלמון.',
     'הניעו בעדינות — ביצה קלוקלת תרגיש כבדה יותר.',
     'הריחו את חלק החיצוני של הקליפה לפני הפתיחה.'),
    ('hq_receiving_2','איכות האוויר: קודי צבעים',
     "איזה צבע מייצג בדרך כלל איכות אוויר 'טובה' ברוב מדדי איכות האוויר?",
     'אדום — מציין רמות זיהום גבוהות.',
     'צהוב — מציין איכות אוויר בינונית.',
     'ירוק — מציין מדידות זיהום נמוכות מאוד.',
     'סגול — מציין את איכות האוויר הנקייה ביותר האפשרית.'),
    ('hq_production_1','איכות מים: סימני בטיחות',
     'מה הוא סימן נפוץ לכך שמי ברז עלולים להיות לא בטוחים לשתייה?',
     'המים נראים קרים מעט יותר מהרגיל.',
     'המים מפיקים ריח חריג לאחר מזיגה.',
     'המים לוקחים יותר זמן לצאת מהברז.',
     'המים מרגישים חמים מעט יותר מהרגיל.'),
    ('hq_production_2','ייצור: יתרונות הברקוד',
     'במה ברקוד מסייע בעיקר לחברות להשתפר?',
     'מראה המוצר ואיכות עיצוב האריזה.',
     'דיוק מעקב המלאי במערכות שרשרת האספקה.',
     'דירוגי שביעות רצון לקוחות ונאמנות למותג.',
     'פריון עובדים וציוני בטיחות במקום העבודה.'),
    ('hq_qclab_1','איכות סביבתית: עצים עירוניים',
     'מדוע עצים חשובים לשיפור איכות הסביבה העירונית?',
     'עצים מספקים בעיקר צל להפחתת טמפרטורות הבניינים.',
     'עצים מפחיתים רעש ומסייעים בסינון מזהמים באוויר.',
     'עצים מעלים בעיקר את ערך הנכסים באזורים עירוניים.',
     'עצים חשובים בעיקר ליצירת בתי גידול לחיות בר.'),
    ('hq_qclab_2','איכות מוצר: בדיקה לפני משלוח',
     'מדוע מוצרי אלקטרוניקה רבים כוללים בדיקות בקרת איכות לפני המשלוח?',
     'כדי לעמוד בתקנות המכס בארצות היעד.',
     'כדי לזהות פגמים לפני שהמוצרים מגיעים ללקוחות הסופיים.',
     'כדי להגדיל את המשקל הכולל של המשלוחים לצורכי ביטוח.',
     'כדי להפחית את הצורך באחריות למוצרים לאחר הרכישה.'),
    ('hq_qaoffice_1','מערכות איכות: תאריכי תפוגה',
     'מה המטרה העיקרית של תאריכי תפוגה על מוצרי מזון ארוזים?',
     'לסייע לקמעונאים לנהל שטח מדף ומחזור מוצרים.',
     'להעריך את תקופת האיכות והבטיחות הצפויה.',
     'למנוע מצרכנים לאכול מזון ישן מדי.',
     'לעמוד בדרישות החוק שנקבעו על ידי רשויות בטיחות המזון.'),
    ('hq_qaoffice_2','אבטחה דיגיטלית: עדכוני תוכנה',
     'מדוע עדכוני תוכנה חשובים לאיכות האבטחה הדיגיטלית?',
     'עדכונים לעיתים קרובות מתקנים פגיעויות ומשפרים את הגנת המערכת.',
     'עדכונים בעיקר מוסיפים תכונות חדשות ומשפרים ביצועים.',
     'עדכונים נדרשים לשמירה על ציות לרישיון התוכנה.',
     'עדכונים מסייעים ליצרנים לעקוב אחר דפוסי שימוש בתוכנה.'),
    ('hq_dispatch_1','איכות דבש: סימנים טבעיים',
     'מה הוא סימן נפוץ לכך שהדבש הוא טבעי ומעובד בצורה מינימלית?',
     'הדבש עשוי להתגבש לאט במהלך תקופות אחסון ארוכות.',
     'הדבש תמיד נשאר שקוף ובהיר לחלוטין.',
     'הדבש אף פעם לא משנה צבע לאחר שמילאו אותו בבקבוקים.',
     'הדבש מייצר שכבת קצף קלה על פני השטח.'),
    ('hq_dispatch_2','בקרת איכות: שיטות דגימה',
     'מדוע מפעלים בודקים לפעמים מוצרים אקראיים במקום כל פריט?',
     'דגימה אקראית יכולה לזהות בצורה יעילה בעיות בתוך אצוות ייצור.',
     'בדיקת כל פריט יקרה מדי ברוב הקשרי הייצור.',
     'בדיקות אקראיות נדרשות על ידי תקני איכות בינלאומיים.',
     'דגימה מפחיתה את הזמן הדרוש לביצוע ביקורות איכות.'),
  ],
}

def build_hq_block(lang_data, indent='    '):
    lines = []
    for q in lang_data:
        qid, title, body, a, b, c, d = q
        def esc(s):
            return s.replace('\\', '\\\\').replace("'", "\\'")
        lines.append(f"{indent}'hq.{qid}.title':                        '{esc(title)}',")
        lines.append(f"{indent}'hq.{qid}.body':                         '{esc(body)}',")
        lines.append(f"{indent}'hq.{qid}.a':                            '{esc(a)}',")
        lines.append(f"{indent}'hq.{qid}.b':                            '{esc(b)}',")
        lines.append(f"{indent}'hq.{qid}.c':                            '{esc(c)}',")
        lines.append(f"{indent}'hq.{qid}.d':                            '{esc(d)}',")
    return '\n'.join(lines)

with open('/home/user/Trial-ofthe-matter/translations.js', 'r', encoding='utf-8') as f:
    content = f.read()

original_len = len(content)

import re

# Replace old HQ blocks (5 questions) with new 10-question blocks
# Old block: from 'hq.hq_receiving.title': to 'hq.hq_dispatch.d': '...',
old_hq_pattern = re.compile(
    r"    'hq\.hq_receiving\.title':.*?'hq\.hq_dispatch\.d':[^\n]+\n",
    re.DOTALL
)

matches = list(old_hq_pattern.finditer(content))
print(f"Found {len(matches)} old HQ blocks to replace")

# Order of languages as they appear in the file (including da)
lang_order = ['en', 'de', 'es', 'pt-BR', 'fr', 'ko', 'da', 'zh-Hans', 'zh-Hant', 'ms', 'ta', 'hi', 'sr-Latn', 'sr-Cyrl', 'he']

if len(matches) != len(lang_order):
    print(f"ERROR: Expected {len(lang_order)} blocks, found {len(matches)}")
    # Debug: show context around each match
    for i, m in enumerate(matches):
        ctx = content[max(0, m.start()-300):m.start()]
        langs_found = re.findall(r"(?:  ([\w-]+): \{|  '([\w-]+)': \{)", ctx)
        last = [a or b for a, b in langs_found][-5:] if langs_found else []
        print(f"  Block {i+1}: last lang headers before = {last}")
else:
    # Apply replacements from end to start to preserve positions
    replacements = []
    for i, match in enumerate(matches):
        lang = lang_order[i]
        if lang in HQ:
            new_block = build_hq_block(HQ[lang]) + '\n'
            replacements.append((match.start(), match.end(), new_block))
        else:
            print(f"WARNING: No HQ data for language {lang}, skipping")

    for start, end, new_text in reversed(replacements):
        content = content[:start] + new_text + content[end:]
    print(f"Replaced {len(replacements)} HQ blocks")

with open('/home/user/Trial-ofthe-matter/translations.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Done. File: {original_len} -> {len(content)} chars")
import subprocess
result = subprocess.run(['node', '--check', '/home/user/Trial-ofthe-matter/translations.js'],
                       capture_output=True, text=True)
if result.returncode == 0:
    print("OK — no syntax errors")
else:
    print("SYNTAX ERROR:", result.stderr[:500])
